// ----------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a compiler emitter: FACTS.Framework.Analysis.Generators.OperationMethod.ControllerEmitter
//
// Changes to this file may cause incorrect behavior and will be lost when the code is regenerated.
// </auto-generated>
// ----------------------------------------------------------------------------------------------------

using System;
using Microsoft.AspNetCore.Mvc;
using FACTS.Framework.Service;

namespace PFML.Service.Controllers.Premium.Registration
{

    public class EmployerRegistrationController : Controller
    {

        [HttpPost]
        [Route("Premium/Registration/EmployerRegistration/ValidateIntroduction")]
        [OperationMethodFilter]
        public PFML.Shared.ViewModels.Premium.Registration.EmployerRegistrationViewModel ValidateIntroduction([FromBody]PFML.Shared.ViewModels.Premium.Registration.EmployerRegistrationViewModel employerRegistrationViewModel)
        {
            return PFML.BusinessLogic.Premium.Registration.EmployerRegistrationLogic.ValidateIntroduction(employerRegistrationViewModel);
        }

        [HttpPost]
        [Route("Premium/Registration/EmployerRegistration/ValidateLiabilityWeeks")]
        [OperationMethodFilter]
        public PFML.Shared.ViewModels.Premium.Registration.EmployerRegistrationViewModel ValidateLiabilityWeeks([FromBody]PFML.Shared.ViewModels.Premium.Registration.EmployerRegistrationViewModel employerRegistrationViewModel)
        {
            return PFML.BusinessLogic.Premium.Registration.EmployerRegistrationLogic.ValidateLiabilityWeeks(employerRegistrationViewModel);
        }

        [HttpPost]
        [Route("Premium/Registration/EmployerRegistration/ValidateEnterPhysicalAddr")]
        [OperationMethodFilter]
        public PFML.Shared.ViewModels.Premium.Registration.EmployerRegistrationViewModel ValidateEnterPhysicalAddr([FromBody]PFML.Shared.ViewModels.Premium.Registration.EmployerRegistrationViewModel employerRegistrationViewModel)
        {
            return PFML.BusinessLogic.Premium.Registration.EmployerRegistrationLogic.ValidateEnterPhysicalAddr(employerRegistrationViewModel);
        }

        [HttpPost]
        [Route("Premium/Registration/EmployerRegistration/ValidateEnterBusiRcdsAddr")]
        [OperationMethodFilter]
        public PFML.Shared.ViewModels.Premium.Registration.EmployerRegistrationViewModel ValidateEnterBusiRcdsAddr([FromBody]PFML.Shared.ViewModels.Premium.Registration.EmployerRegistrationViewModel employerRegistrationViewModel)
        {
            return PFML.BusinessLogic.Premium.Registration.EmployerRegistrationLogic.ValidateEnterBusiRcdsAddr(employerRegistrationViewModel);
        }

        [HttpPost]
        [Route("Premium/Registration/EmployerRegistration/SubmitRegistration")]
        [OperationMethodFilter]
        public PFML.Shared.ViewModels.Premium.Registration.EmployerRegistrationViewModel SubmitRegistration([FromBody]PFML.Shared.ViewModels.Premium.Registration.EmployerRegistrationViewModel employerRegistrationViewModel)
        {
            return PFML.BusinessLogic.Premium.Registration.EmployerRegistrationLogic.SubmitRegistration(employerRegistrationViewModel);
        }

        [HttpPost]
        [Route("Premium/Registration/EmployerRegistration/ValidateEnterBusinessInfoCont")]
        [OperationMethodFilter]
        public PFML.Shared.ViewModels.Premium.Registration.EmployerRegistrationViewModel ValidateEnterBusinessInfoCont([FromBody]PFML.Shared.ViewModels.Premium.Registration.EmployerRegistrationViewModel employerRegistrationViewModel)
        {
            return PFML.BusinessLogic.Premium.Registration.EmployerRegistrationLogic.ValidateEnterBusinessInfoCont(employerRegistrationViewModel);
        }

        [HttpPost]
        [Route("Premium/Registration/EmployerRegistration/ValidateEnterBusinessInfo")]
        [OperationMethodFilter]
        public PFML.Shared.ViewModels.Premium.Registration.EmployerRegistrationViewModel ValidateEnterBusinessInfo([FromBody]PFML.Shared.ViewModels.Premium.Registration.EmployerRegistrationViewModel employerRegistrationViewModel)
        {
            return PFML.BusinessLogic.Premium.Registration.EmployerRegistrationLogic.ValidateEnterBusinessInfo(employerRegistrationViewModel);
        }

        [HttpPost]
        [Route("Premium/Registration/EmployerRegistration/ValidateEmpIdentification")]
        [OperationMethodFilter]
        public PFML.Shared.ViewModels.Premium.Registration.EmployerRegistrationViewModel ValidateEmpIdentification([FromBody]PFML.Shared.ViewModels.Premium.Registration.EmployerRegistrationViewModel employerRegistrationViewModel)
        {
            return PFML.BusinessLogic.Premium.Registration.EmployerRegistrationLogic.ValidateEmpIdentification(employerRegistrationViewModel);
        }

        [HttpPost]
        [Route("Premium/Registration/EmployerRegistration/ValidateAdminInfo")]
        [OperationMethodFilter]
        public PFML.Shared.ViewModels.Premium.Registration.EmployerRegistrationViewModel ValidateAdminInfo([FromBody]PFML.Shared.ViewModels.Premium.Registration.EmployerRegistrationViewModel employerRegistrationViewModel)
        {
            return PFML.BusinessLogic.Premium.Registration.EmployerRegistrationLogic.ValidateAdminInfo(employerRegistrationViewModel);
        }

    }

}
