// ----------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a compiler emitter: FACTS.Framework.Analysis.Generators.OperationMethod.ControllerEmitter
//
// Changes to this file may cause incorrect behavior and will be lost when the code is regenerated.
// </auto-generated>
// ----------------------------------------------------------------------------------------------------

using System;
using Microsoft.AspNetCore.Mvc;
using FACTS.Framework.Service;

namespace PFML.Service.Controllers.Premium.Waiver.VPRequest
{

    public class VPRequestController : Controller
    {

        [HttpPost]
        [Route("Premium/Waiver/VPRequest/GetList")]
        [OperationMethodFilter]
        public System.Collections.Generic.List<PFML.Shared.Model.DbDtos.VoluntaryPlanWaiverRequestDto> GetList([FromBody]int EmployerId)
        {
            return PFML.BusinessLogic.Premium.Waiver.VPRequest.VPRequestLogic.GetList(EmployerId);
        }

        [HttpPost]
        [Route("Premium/Waiver/VPRequest/GetRequest")]
        [OperationMethodFilter]
        public PFML.Shared.Model.DbDtos.VoluntaryPlanWaiverRequestDto GetRequest([FromBody]PFML.Shared.Model.DbDtos.VoluntaryPlanWaiverRequestDto VoluntaryPlanWaiverRequestDto)
        {
            return PFML.BusinessLogic.Premium.Waiver.VPRequest.VPRequestLogic.GetRequest(VoluntaryPlanWaiverRequestDto);
        }

        [HttpPost]
        [Route("Premium/Waiver/VPRequest/SubmitRequest")]
        [OperationMethodFilter]
        public System.Collections.Generic.List<PFML.Shared.Model.DbDtos.VoluntaryPlanWaiverRequestDto> SubmitRequest([FromBody]PFML.Shared.Model.DbDtos.VoluntaryPlanWaiverRequestDto VPRequestForm)
        {
            return PFML.BusinessLogic.Premium.Waiver.VPRequest.VPRequestLogic.SubmitRequest(VPRequestForm);
        }

        [HttpPost]
        [Route("Premium/Waiver/VPRequest/SetData")]
        [OperationMethodFilter]
        public PFML.Shared.Model.DbDtos.VoluntaryPlanWaiverRequestDto SetData()
        {
            return PFML.BusinessLogic.Premium.Waiver.VPRequest.VPRequestLogic.SetData();
        }

    }

}
