// ----------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a compiler emitter: FACTS.Framework.Analysis.Generators.DAL.EntityEmitter
//
// Changes to this file may cause incorrect behavior and will be lost when the code is regenerated.
// </auto-generated>
// ----------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Linq;
using PFML.Shared.Model.DbDtos;
using FACTS.Framework.DAL;

namespace PFML.DAL.Model.DbEntities
{

    /// <summary>[EmployerUnit]</summary>
    [Table("EmployerUnit", Schema="dbo")]
    public class EmployerUnit : BaseEntity
    {

        /// <summary>[CountyCode]</summary>
        [Required]
        [MaxLength(20)]
        [Column("CountyCode")]
        public string CountyCode { get; set; }

        /// <summary>[CreateDateTime]</summary>
        [Required]
        [Column("CreateDateTime")]
        public DateTime CreateDateTime { get; set; }

        /// <summary>[CreateUserId]</summary>
        [Required]
        [MaxLength(50)]
        [Column("CreateUserId")]
        public string CreateUserId { get; set; }

        /// <summary>[DoingBusinessAsName]</summary>
        [MaxLength(80)]
        [Column("DoingBusinessAsName")]
        public string DoingBusinessAsName { get; set; }

        /// <summary>[EmployerId]</summary>
        [Key]
        [Required]
        [Column("EmployerId", Order=1)]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int EmployerId { get; set; }

        /// <summary>[EmployerUnitSeqNo]</summary>
        [Key]
        [Required]
        [Column("EmployerUnitSeqNo", Order=2)]
        public int EmployerUnitSeqNo { get; set; }

        /// <summary>[FirstWageDate]</summary>
        [Column("FirstWageDate")]
        public DateTime? FirstWageDate { get; set; }

        /// <summary>[StatusCode]</summary>
        [Required]
        [MaxLength(20)]
        [Column("StatusCode")]
        public string StatusCode { get; set; }

        /// <summary>[StatusDate]</summary>
        [Required]
        [Column("StatusDate")]
        public DateTime StatusDate { get; set; }

        /// <summary>[UpdateDateTime]</summary>
        [Required]
        [Column("UpdateDateTime")]
        [ConcurrencyCheck]
        public DateTime UpdateDateTime { get; set; }

        /// <summary>[UpdateNumber]</summary>
        [Column("UpdateNumber")]
        public int? UpdateNumber { get; set; }

        /// <summary>[UpdateProcess]</summary>
        [MaxLength(100)]
        [Column("UpdateProcess")]
        public string UpdateProcess { get; set; }

        /// <summary>[UpdateUserId]</summary>
        [Required]
        [MaxLength(50)]
        [Column("UpdateUserId")]
        public string UpdateUserId { get; set; }

        public virtual Employer Employer { get; set; }

        private ICollection<AddressLink> addressLinks { get; set; }
        public virtual ICollection<AddressLink> AddressLinks { get { return addressLinks ?? (addressLinks = new Collection<AddressLink>()); } protected set { addressLinks = value; } }

        public override void SetAuditFields(EntityState state)
        {
            string username = FACTS.Framework.Service.Context.UserName ?? "UNKNOWN";
            DateTime timestamp = FACTS.Framework.Utility.DateTimeUtil.Now;

            if (state == EntityState.Added)
            {
                CreateUserId = username;
                CreateDateTime = new System.Data.SqlTypes.SqlDateTime(timestamp).Value;
                UpdateUserId = username;
                UpdateDateTime = new System.Data.SqlTypes.SqlDateTime(timestamp).Value;
                UpdateNumber = 0;
                UpdateProcess = FACTS.Framework.Utility.StringUtil.CapLength(FACTS.Framework.Service.Context.Process.ToString(), 100);
            }
            else if (state == EntityState.Modified)
            {
                UpdateUserId = username;
                UpdateDateTime = new System.Data.SqlTypes.SqlDateTime(timestamp).Value;
                UpdateNumber = (UpdateNumber ?? 0) + 1;
                UpdateProcess = FACTS.Framework.Utility.StringUtil.CapLength(FACTS.Framework.Service.Context.Process.ToString(), 100);
            }
        }

        internal static void ModelCreating(DbModelBuilder builder)
        {
            builder.Entity<EmployerUnit>().Property(x => x.CountyCode).IsUnicode(false);
            builder.Entity<EmployerUnit>().Property(x => x.CreateUserId).IsUnicode(false);
            builder.Entity<EmployerUnit>().Property(x => x.DoingBusinessAsName).IsUnicode(false);
            builder.Entity<EmployerUnit>().Property(x => x.StatusCode).IsUnicode(false);
            builder.Entity<EmployerUnit>().Property(x => x.UpdateProcess).IsUnicode(false);
            builder.Entity<EmployerUnit>().Property(x => x.UpdateUserId).IsUnicode(false);
            builder.Entity<EmployerUnit>().HasRequired(x => x.Employer).WithMany(x => x.EmployerUnits).HasForeignKey(x => x.EmployerId);
        }

        /// <summary>Convert from EmployerUnit entity to DTO</summary>
        /// <param name="dbContext">DB Context to use for setting DTO state</param>
        /// <param name="dto">DTO to use if already created instead of creating new one (can be inherited class instead as opposed to base class)</param>
        /// <param name="entityDtos">Used internally to track which entities have been converted to DTO's already (to avoid re-converting when circularly referenced)</param>
        /// <returns>Resultant EmployerUnit DTO</returns>
        public EmployerUnitDto ToDtoDeep(FACTS.Framework.DAL.DbContext dbContext, EmployerUnitDto dto = null, Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto> entityDtos = null)
        {
            entityDtos = entityDtos ?? new Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto>();
            if (entityDtos.ContainsKey(this))
            {
                return (EmployerUnitDto)entityDtos[this];
            }

            dto = ToDto(dto);
            entityDtos.Add(this, dto);

            System.Data.Entity.Infrastructure.DbEntityEntry<EmployerUnit> entry = dbContext?.Entry(this);
            dto.IsNew = (entry?.State == EntityState.Added);
            dto.IsDeleted = (entry?.State == EntityState.Deleted);

            if (entry?.Reference(x => x.Employer)?.IsLoaded == true)
            {
                dto.Employer = Employer?.ToDtoDeep(dbContext, entityDtos: entityDtos);
            }
            if (entry?.Collection(x => x.AddressLinks)?.IsLoaded == true)
            {
                foreach (AddressLink addressLink in AddressLinks)
                {
                    dto.AddressLinks.Add(addressLink.ToDtoDeep(dbContext, entityDtos: entityDtos));
                }
            }

            return dto;
        }

        /// <summary>Convert from EmployerUnit entity to DTO w/o checking entity state or entity navigation</summary>
        /// <param name="dto">DTO to use if already created instead of creating new one (can be inherited class instead as opposed to base class)</param>
        /// <returns>Resultant EmployerUnit DTO</returns>
        public EmployerUnitDto ToDto(EmployerUnitDto dto = null)
        {

            dto = dto ?? new EmployerUnitDto();
            dto.IsNew = false;

            dto.CountyCode = CountyCode;
            dto.CreateDateTime = CreateDateTime;
            dto.CreateUserId = CreateUserId;
            dto.DoingBusinessAsName = DoingBusinessAsName;
            dto.EmployerId = EmployerId;
            dto.EmployerUnitSeqNo = EmployerUnitSeqNo;
            dto.FirstWageDate = FirstWageDate;
            dto.StatusCode = StatusCode;
            dto.StatusDate = StatusDate;
            dto.UpdateDateTime = UpdateDateTime;
            dto.UpdateNumber = UpdateNumber;
            dto.UpdateProcess = UpdateProcess;
            dto.UpdateUserId = UpdateUserId;

            return dto;
        }

        /// <summary>Convert from EmployerUnit DTO to entity</summary>
        /// <param name="dbContext">DB Context to use for attaching entity</param>
        /// <param name="dto">DTO to convert from</param>
        /// <param name="dtoEntities">Used internally to track which dtos have been converted to entites already (to avoid re-converting when circularly referenced)</param>
        /// <returns>Resultant EmployerUnit entity</returns>
        public static EmployerUnit FromDto(FACTS.Framework.DAL.DbContext dbContext, EmployerUnitDto dto, Dictionary<FACTS.Framework.Dto.BaseDto, BaseEntity> dtoEntities = null)
        {
            dtoEntities = dtoEntities ?? new Dictionary<FACTS.Framework.Dto.BaseDto, BaseEntity>();
            if (dtoEntities.ContainsKey(dto))
            {
                return (EmployerUnit)dtoEntities[dto];
            }

            EmployerUnit entity = new EmployerUnit();
            dtoEntities.Add(dto, entity);

            entity.CountyCode = dto.CountyCode;
            entity.CreateDateTime = dto.CreateDateTime;
            entity.CreateUserId = dto.CreateUserId;
            entity.DoingBusinessAsName = dto.DoingBusinessAsName;
            entity.EmployerId = dto.EmployerId;
            entity.EmployerUnitSeqNo = dto.EmployerUnitSeqNo;
            entity.FirstWageDate = dto.FirstWageDate;
            entity.StatusCode = dto.StatusCode;
            entity.StatusDate = dto.StatusDate;
            entity.UpdateDateTime = dto.UpdateDateTime;
            entity.UpdateNumber = dto.UpdateNumber;
            entity.UpdateProcess = dto.UpdateProcess;
            entity.UpdateUserId = dto.UpdateUserId;

            entity.Employer = (dto.Employer == null) ? null : Employer.FromDto(dbContext, dto.Employer, dtoEntities);
            if (dto.AddressLinks != null)
            {
                foreach (AddressLinkDto addressLink in dto.AddressLinks)
                {
                    entity.AddressLinks.Add(DbEntities.AddressLink.FromDto(dbContext, addressLink, dtoEntities));
                }
            }

            if (dbContext != null)
            {
                dbContext.Entry(entity).State = (dto.IsNew ? EntityState.Added : (dto.IsDeleted ? EntityState.Deleted : EntityState.Modified));
            }

            return entity;
        }

    }

    /// <summary>Extension methods related to EmployerUnit entity</summary>
    public static class EmployerUnitExtension
    {

        /// <summary>Convert IEnumerable EmployerUnit to list of DTOs</summary>
        /// <param name="entities">IEnumerable EmployerUnits</param>
        /// <param name="dbContext">DB Context to use for setting state of DTO</param>
        /// <returns>List of DTO EmployerUnits</returns>
        public static List<EmployerUnitDto> ToDtoListDeep(this IEnumerable<EmployerUnit> entities, FACTS.Framework.DAL.DbContext dbContext)
        {
            Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto> entityDtos = new Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto>();
            List<EmployerUnitDto> dtos = new List<EmployerUnitDto>();
            foreach (EmployerUnit entity in entities)
            {
                dtos.Add(entity.ToDtoDeep(dbContext, entityDtos: entityDtos));
            }
            return dtos;
        }

        /// <summary>Convert L2E EmployerUnit to list of DTOs</summary>
        /// <param name="entities">L2E EmployerUnits</param>
        /// <param name="dbContext">DB Context to use for setting state of DTO</param>
        /// <returns>List of DTO EmployerUnits</returns>
        public static List<EmployerUnitDto> ToDtoListDeep(this IQueryable<EmployerUnit> entities, FACTS.Framework.DAL.DbContext dbContext)
        {
            Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto> entityDtos = new Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto>();
            List<EmployerUnitDto> dtos = new List<EmployerUnitDto>();
            foreach (EmployerUnit entity in entities)
            {
                dtos.Add(entity.ToDtoDeep(dbContext, entityDtos: entityDtos));
            }
            return dtos;
        }

        /// <summary>Convert L2E EmployerUnit to list of customized DTOs</summary>
        /// <typeparam name="T">Custom DTO derived from EmployerUnitDto</typeparam>
        /// <param name="entities">L2E EmployerUnits</param>
        /// <param name="dbContext">DB Context to use for setting state of DTO</param>
        /// <returns>List of DTO customized EmployerUnits</returns>
        public static List<T> ToDtoListDeep<T>(this IQueryable<EmployerUnit> entities, FACTS.Framework.DAL.DbContext dbContext) where T : EmployerUnitDto, new()
        {
            Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto> entityDtos = new Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto>();
            List<T> dtos = new List<T>();
            foreach (EmployerUnit entity in entities)
            {
                dtos.Add((T)entity.ToDtoDeep(dbContext, new T(), entityDtos));
            }
            return dtos;
        }

        /// <summary>Convert IEnumerable EmployerUnit to list of DTOs w/o checking entity state or entity navigation</summary>
        /// <param name="entities">IEnumerable EmployerUnits</param>
        /// <returns>List of DTO EmployerUnits</returns>
        public static List<EmployerUnitDto> ToDtoList(this IEnumerable<EmployerUnit> entities)
        {
            List<EmployerUnitDto> dtos = new List<EmployerUnitDto>();
            foreach (EmployerUnit entity in entities)
            {
                dtos.Add(entity.ToDto());
            }
            return dtos;
        }

        /// <summary>Convert L2E EmployerUnit to list of DTOs w/o checking entity state or entity navigation</summary>
        /// <param name="entities">L2E EmployerUnits</param>
        /// <returns>List of DTO EmployerUnits</returns>
        public static List<EmployerUnitDto> ToDtoList(this IQueryable<EmployerUnit> entities)
        {
            List<EmployerUnitDto> dtos = new List<EmployerUnitDto>();
            foreach (EmployerUnit entity in entities)
            {
                dtos.Add(entity.ToDto());
            }
            return dtos;
        }

        /// <summary>Convert L2E EmployerUnit to list of customized DTOs w/o checking entity state or entity navigation</summary>
        /// <typeparam name="T">Custom DTO derived from EmployerUnitDto</typeparam>
        /// <param name="entities">L2E EmployerUnits</param>
        /// <returns>List of DTO customized EmployerUnits</returns>
        public static List<T> ToDtoList<T>(this IQueryable<EmployerUnit> entities) where T : EmployerUnitDto, new()
        {
            List<T> dtos = new List<T>();
            foreach (EmployerUnit entity in entities)
            {
                dtos.Add((T)entity.ToDto(new T()));
            }
            return dtos;
        }

    }

}
