// ----------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a compiler emitter: FACTS.Framework.Analysis.Generators.DAL.EntityEmitter
//
// Changes to this file may cause incorrect behavior and will be lost when the code is regenerated.
// </auto-generated>
// ----------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Linq;
using PFML.Shared.Model.DbDtos;
using FACTS.Framework.DAL;

namespace PFML.DAL.Model.DbEntities
{

    /// <summary>[LookupCode]</summary>
    [Table("LookupCode", Schema="dbo")]
    public class LookupCode : BaseEntity
    {

        /// <summary>[Code]</summary>
        [Key]
        [Required]
        [MaxLength(20)]
        [Column("Code", Order=2)]
        public string Code { get; set; }

        /// <summary>[CreateDateTime]</summary>
        [Required]
        [Column("CreateDateTime")]
        public DateTime CreateDateTime { get; set; }

        /// <summary>[CreateUserId]</summary>
        [Required]
        [MaxLength(50)]
        [Column("CreateUserId")]
        public string CreateUserId { get; set; }

        /// <summary>[Description]</summary>
        [MaxLength(500)]
        [Column("Description")]
        public string Description { get; set; }

        /// <summary>[Display]</summary>
        [Required]
        [MaxLength(50)]
        [Column("Display")]
        public string Display { get; set; }

        /// <summary>[Name]</summary>
        [Key]
        [Required]
        [MaxLength(50)]
        [Column("Name", Order=1)]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public string Name { get; set; }

        /// <summary>[UpdateDateTime]</summary>
        [Required]
        [Column("UpdateDateTime")]
        [ConcurrencyCheck]
        public DateTime UpdateDateTime { get; set; }

        /// <summary>[UpdateNumber]</summary>
        [Column("UpdateNumber")]
        public int? UpdateNumber { get; set; }

        /// <summary>[UpdateProcess]</summary>
        [MaxLength(100)]
        [Column("UpdateProcess")]
        public string UpdateProcess { get; set; }

        /// <summary>[UpdateUserId]</summary>
        [Required]
        [MaxLength(50)]
        [Column("UpdateUserId")]
        public string UpdateUserId { get; set; }

        public virtual LookupName LookupName { get; set; }

        private ICollection<LookupValue> lookupValues { get; set; }
        public virtual ICollection<LookupValue> LookupValues { get { return lookupValues ?? (lookupValues = new Collection<LookupValue>()); } protected set { lookupValues = value; } }

        public override void SetAuditFields(EntityState state)
        {
            string username = FACTS.Framework.Service.Context.UserName ?? "UNKNOWN";
            DateTime timestamp = FACTS.Framework.Utility.DateTimeUtil.Now;

            if (state == EntityState.Added)
            {
                CreateUserId = username;
                CreateDateTime = new System.Data.SqlTypes.SqlDateTime(timestamp).Value;
                UpdateUserId = username;
                UpdateDateTime = new System.Data.SqlTypes.SqlDateTime(timestamp).Value;
                UpdateNumber = 0;
                UpdateProcess = FACTS.Framework.Utility.StringUtil.CapLength(FACTS.Framework.Service.Context.Process.ToString(), 100);
            }
            else if (state == EntityState.Modified)
            {
                UpdateUserId = username;
                UpdateDateTime = new System.Data.SqlTypes.SqlDateTime(timestamp).Value;
                UpdateNumber = (UpdateNumber ?? 0) + 1;
                UpdateProcess = FACTS.Framework.Utility.StringUtil.CapLength(FACTS.Framework.Service.Context.Process.ToString(), 100);
            }
        }

        internal static void ModelCreating(DbModelBuilder builder)
        {
            builder.Entity<LookupCode>().Property(x => x.Code).IsUnicode(false);
            builder.Entity<LookupCode>().Property(x => x.CreateUserId).IsUnicode(false);
            builder.Entity<LookupCode>().Property(x => x.Description).IsUnicode(false);
            builder.Entity<LookupCode>().Property(x => x.Display).IsUnicode(false);
            builder.Entity<LookupCode>().Property(x => x.Name).IsUnicode(false);
            builder.Entity<LookupCode>().Property(x => x.UpdateProcess).IsUnicode(false);
            builder.Entity<LookupCode>().Property(x => x.UpdateUserId).IsUnicode(false);
            builder.Entity<LookupCode>().HasRequired(x => x.LookupName).WithMany(x => x.LookupCodes).HasForeignKey(x => x.Name);
        }

        /// <summary>Convert from LookupCode entity to DTO</summary>
        /// <param name="dbContext">DB Context to use for setting DTO state</param>
        /// <param name="dto">DTO to use if already created instead of creating new one (can be inherited class instead as opposed to base class)</param>
        /// <param name="entityDtos">Used internally to track which entities have been converted to DTO's already (to avoid re-converting when circularly referenced)</param>
        /// <returns>Resultant LookupCode DTO</returns>
        public LookupCodeDto ToDtoDeep(FACTS.Framework.DAL.DbContext dbContext, LookupCodeDto dto = null, Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto> entityDtos = null)
        {
            entityDtos = entityDtos ?? new Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto>();
            if (entityDtos.ContainsKey(this))
            {
                return (LookupCodeDto)entityDtos[this];
            }

            dto = ToDto(dto);
            entityDtos.Add(this, dto);

            System.Data.Entity.Infrastructure.DbEntityEntry<LookupCode> entry = dbContext?.Entry(this);
            dto.IsNew = (entry?.State == EntityState.Added);
            dto.IsDeleted = (entry?.State == EntityState.Deleted);

            if (entry?.Reference(x => x.LookupName)?.IsLoaded == true)
            {
                dto.LookupName = LookupName?.ToDtoDeep(dbContext, entityDtos: entityDtos);
            }
            if (entry?.Collection(x => x.LookupValues)?.IsLoaded == true)
            {
                foreach (LookupValue lookupValue in LookupValues)
                {
                    dto.LookupValues.Add(lookupValue.ToDtoDeep(dbContext, entityDtos: entityDtos));
                }
            }

            return dto;
        }

        /// <summary>Convert from LookupCode entity to DTO w/o checking entity state or entity navigation</summary>
        /// <param name="dto">DTO to use if already created instead of creating new one (can be inherited class instead as opposed to base class)</param>
        /// <returns>Resultant LookupCode DTO</returns>
        public LookupCodeDto ToDto(LookupCodeDto dto = null)
        {

            dto = dto ?? new LookupCodeDto();
            dto.IsNew = false;

            dto.Code = Code;
            dto.CreateDateTime = CreateDateTime;
            dto.CreateUserId = CreateUserId;
            dto.Description = Description;
            dto.Display = Display;
            dto.Name = Name;
            dto.UpdateDateTime = UpdateDateTime;
            dto.UpdateNumber = UpdateNumber;
            dto.UpdateProcess = UpdateProcess;
            dto.UpdateUserId = UpdateUserId;

            return dto;
        }

        /// <summary>Convert from LookupCode DTO to entity</summary>
        /// <param name="dbContext">DB Context to use for attaching entity</param>
        /// <param name="dto">DTO to convert from</param>
        /// <param name="dtoEntities">Used internally to track which dtos have been converted to entites already (to avoid re-converting when circularly referenced)</param>
        /// <returns>Resultant LookupCode entity</returns>
        public static LookupCode FromDto(FACTS.Framework.DAL.DbContext dbContext, LookupCodeDto dto, Dictionary<FACTS.Framework.Dto.BaseDto, BaseEntity> dtoEntities = null)
        {
            dtoEntities = dtoEntities ?? new Dictionary<FACTS.Framework.Dto.BaseDto, BaseEntity>();
            if (dtoEntities.ContainsKey(dto))
            {
                return (LookupCode)dtoEntities[dto];
            }

            LookupCode entity = new LookupCode();
            dtoEntities.Add(dto, entity);

            entity.Code = dto.Code;
            entity.CreateDateTime = dto.CreateDateTime;
            entity.CreateUserId = dto.CreateUserId;
            entity.Description = dto.Description;
            entity.Display = dto.Display;
            entity.Name = dto.Name;
            entity.UpdateDateTime = dto.UpdateDateTime;
            entity.UpdateNumber = dto.UpdateNumber;
            entity.UpdateProcess = dto.UpdateProcess;
            entity.UpdateUserId = dto.UpdateUserId;

            entity.LookupName = (dto.LookupName == null) ? null : LookupName.FromDto(dbContext, dto.LookupName, dtoEntities);
            if (dto.LookupValues != null)
            {
                foreach (LookupValueDto lookupValue in dto.LookupValues)
                {
                    entity.LookupValues.Add(DbEntities.LookupValue.FromDto(dbContext, lookupValue, dtoEntities));
                }
            }

            if (dbContext != null)
            {
                dbContext.Entry(entity).State = (dto.IsNew ? EntityState.Added : (dto.IsDeleted ? EntityState.Deleted : EntityState.Modified));
            }

            return entity;
        }

    }

    /// <summary>Extension methods related to LookupCode entity</summary>
    public static class LookupCodeExtension
    {

        /// <summary>Convert IEnumerable LookupCode to list of DTOs</summary>
        /// <param name="entities">IEnumerable LookupCodes</param>
        /// <param name="dbContext">DB Context to use for setting state of DTO</param>
        /// <returns>List of DTO LookupCodes</returns>
        public static List<LookupCodeDto> ToDtoListDeep(this IEnumerable<LookupCode> entities, FACTS.Framework.DAL.DbContext dbContext)
        {
            Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto> entityDtos = new Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto>();
            List<LookupCodeDto> dtos = new List<LookupCodeDto>();
            foreach (LookupCode entity in entities)
            {
                dtos.Add(entity.ToDtoDeep(dbContext, entityDtos: entityDtos));
            }
            return dtos;
        }

        /// <summary>Convert L2E LookupCode to list of DTOs</summary>
        /// <param name="entities">L2E LookupCodes</param>
        /// <param name="dbContext">DB Context to use for setting state of DTO</param>
        /// <returns>List of DTO LookupCodes</returns>
        public static List<LookupCodeDto> ToDtoListDeep(this IQueryable<LookupCode> entities, FACTS.Framework.DAL.DbContext dbContext)
        {
            Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto> entityDtos = new Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto>();
            List<LookupCodeDto> dtos = new List<LookupCodeDto>();
            foreach (LookupCode entity in entities)
            {
                dtos.Add(entity.ToDtoDeep(dbContext, entityDtos: entityDtos));
            }
            return dtos;
        }

        /// <summary>Convert L2E LookupCode to list of customized DTOs</summary>
        /// <typeparam name="T">Custom DTO derived from LookupCodeDto</typeparam>
        /// <param name="entities">L2E LookupCodes</param>
        /// <param name="dbContext">DB Context to use for setting state of DTO</param>
        /// <returns>List of DTO customized LookupCodes</returns>
        public static List<T> ToDtoListDeep<T>(this IQueryable<LookupCode> entities, FACTS.Framework.DAL.DbContext dbContext) where T : LookupCodeDto, new()
        {
            Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto> entityDtos = new Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto>();
            List<T> dtos = new List<T>();
            foreach (LookupCode entity in entities)
            {
                dtos.Add((T)entity.ToDtoDeep(dbContext, new T(), entityDtos));
            }
            return dtos;
        }

        /// <summary>Convert IEnumerable LookupCode to list of DTOs w/o checking entity state or entity navigation</summary>
        /// <param name="entities">IEnumerable LookupCodes</param>
        /// <returns>List of DTO LookupCodes</returns>
        public static List<LookupCodeDto> ToDtoList(this IEnumerable<LookupCode> entities)
        {
            List<LookupCodeDto> dtos = new List<LookupCodeDto>();
            foreach (LookupCode entity in entities)
            {
                dtos.Add(entity.ToDto());
            }
            return dtos;
        }

        /// <summary>Convert L2E LookupCode to list of DTOs w/o checking entity state or entity navigation</summary>
        /// <param name="entities">L2E LookupCodes</param>
        /// <returns>List of DTO LookupCodes</returns>
        public static List<LookupCodeDto> ToDtoList(this IQueryable<LookupCode> entities)
        {
            List<LookupCodeDto> dtos = new List<LookupCodeDto>();
            foreach (LookupCode entity in entities)
            {
                dtos.Add(entity.ToDto());
            }
            return dtos;
        }

        /// <summary>Convert L2E LookupCode to list of customized DTOs w/o checking entity state or entity navigation</summary>
        /// <typeparam name="T">Custom DTO derived from LookupCodeDto</typeparam>
        /// <param name="entities">L2E LookupCodes</param>
        /// <returns>List of DTO customized LookupCodes</returns>
        public static List<T> ToDtoList<T>(this IQueryable<LookupCode> entities) where T : LookupCodeDto, new()
        {
            List<T> dtos = new List<T>();
            foreach (LookupCode entity in entities)
            {
                dtos.Add((T)entity.ToDto(new T()));
            }
            return dtos;
        }

    }

}
