// ----------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a compiler emitter: FACTS.Framework.Analysis.Generators.DAL.EntityEmitter
//
// Changes to this file may cause incorrect behavior and will be lost when the code is regenerated.
// </auto-generated>
// ----------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Linq;
using PFML.Shared.Model.DbDtos;
using FACTS.Framework.DAL;

namespace PFML.DAL.Model.DbEntities
{

    /// <summary>[VoluntaryPlanWaiverRequest]</summary>
    [Table("VoluntaryPlanWaiverRequest", Schema="dbo")]
    public class VoluntaryPlanWaiverRequest : BaseEntity
    {

        /// <summary>[CreateDateTime]</summary>
        [Required]
        [Column("CreateDateTime")]
        public DateTime CreateDateTime { get; set; }

        /// <summary>[CreateUserId]</summary>
        [Required]
        [MaxLength(50)]
        [Column("CreateUserId")]
        public string CreateUserId { get; set; }

        /// <summary>[EmployerId]</summary>
        [Required]
        [Column("EmployerId")]
        public int EmployerId { get; set; }

        /// <summary>[EndDate]</summary>
        [Required]
        [Column("EndDate")]
        public DateTime EndDate { get; set; }

        /// <summary>[FormId]</summary>
        [Key]
        [Required]
        [Column("FormId", Order=1)]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int FormId { get; set; }

        /// <summary>[IsVoluntaryPlanWaiverRequestAcknowledged]</summary>
        [Required]
        [Column("IsVoluntaryPlanWaiverRequestAcknowledged")]
        public bool IsVoluntaryPlanWaiverRequestAcknowledged { get; set; }

        /// <summary>[StartDate]</summary>
        [Required]
        [Column("StartDate")]
        public DateTime StartDate { get; set; }

        /// <summary>[UpdateDateTime]</summary>
        [Required]
        [Column("UpdateDateTime")]
        [ConcurrencyCheck]
        public DateTime UpdateDateTime { get; set; }

        /// <summary>[UpdateNumber]</summary>
        [Column("UpdateNumber")]
        public int? UpdateNumber { get; set; }

        /// <summary>[UpdateProcess]</summary>
        [MaxLength(100)]
        [Column("UpdateProcess")]
        public string UpdateProcess { get; set; }

        /// <summary>[UpdateUserId]</summary>
        [Required]
        [MaxLength(50)]
        [Column("UpdateUserId")]
        public string UpdateUserId { get; set; }

        public virtual Employer Employer { get; set; }

        public virtual Form Form { get; set; }

        private ICollection<VoluntaryPlanWaiverRequestType> voluntaryPlanWaiverRequestTypes { get; set; }
        public virtual ICollection<VoluntaryPlanWaiverRequestType> VoluntaryPlanWaiverRequestTypes { get { return voluntaryPlanWaiverRequestTypes ?? (voluntaryPlanWaiverRequestTypes = new Collection<VoluntaryPlanWaiverRequestType>()); } protected set { voluntaryPlanWaiverRequestTypes = value; } }

        public override void SetAuditFields(EntityState state)
        {
            string username = FACTS.Framework.Service.Context.UserName ?? "UNKNOWN";
            DateTime timestamp = FACTS.Framework.Utility.DateTimeUtil.Now;

            if (state == EntityState.Added)
            {
                CreateUserId = username;
                CreateDateTime = new System.Data.SqlTypes.SqlDateTime(timestamp).Value;
                UpdateUserId = username;
                UpdateDateTime = new System.Data.SqlTypes.SqlDateTime(timestamp).Value;
                UpdateNumber = 0;
                UpdateProcess = FACTS.Framework.Utility.StringUtil.CapLength(FACTS.Framework.Service.Context.Process.ToString(), 100);
            }
            else if (state == EntityState.Modified)
            {
                UpdateUserId = username;
                UpdateDateTime = new System.Data.SqlTypes.SqlDateTime(timestamp).Value;
                UpdateNumber = (UpdateNumber ?? 0) + 1;
                UpdateProcess = FACTS.Framework.Utility.StringUtil.CapLength(FACTS.Framework.Service.Context.Process.ToString(), 100);
            }
        }

        internal static void ModelCreating(DbModelBuilder builder)
        {
            builder.Entity<VoluntaryPlanWaiverRequest>().Property(x => x.CreateUserId).IsUnicode(false);
            builder.Entity<VoluntaryPlanWaiverRequest>().Property(x => x.UpdateProcess).IsUnicode(false);
            builder.Entity<VoluntaryPlanWaiverRequest>().Property(x => x.UpdateUserId).IsUnicode(false);
            builder.Entity<VoluntaryPlanWaiverRequest>().HasRequired(x => x.Employer).WithMany(x => x.VoluntaryPlanWaiverRequests).HasForeignKey(x => x.EmployerId);
            builder.Entity<VoluntaryPlanWaiverRequest>().HasRequired(x => x.Form).WithRequiredDependent(x => x.VoluntaryPlanWaiverRequest);
        }

        /// <summary>Convert from VoluntaryPlanWaiverRequest entity to DTO</summary>
        /// <param name="dbContext">DB Context to use for setting DTO state</param>
        /// <param name="dto">DTO to use if already created instead of creating new one (can be inherited class instead as opposed to base class)</param>
        /// <param name="entityDtos">Used internally to track which entities have been converted to DTO's already (to avoid re-converting when circularly referenced)</param>
        /// <returns>Resultant VoluntaryPlanWaiverRequest DTO</returns>
        public VoluntaryPlanWaiverRequestDto ToDtoDeep(FACTS.Framework.DAL.DbContext dbContext, VoluntaryPlanWaiverRequestDto dto = null, Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto> entityDtos = null)
        {
            entityDtos = entityDtos ?? new Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto>();
            if (entityDtos.ContainsKey(this))
            {
                return (VoluntaryPlanWaiverRequestDto)entityDtos[this];
            }

            dto = ToDto(dto);
            entityDtos.Add(this, dto);

            System.Data.Entity.Infrastructure.DbEntityEntry<VoluntaryPlanWaiverRequest> entry = dbContext?.Entry(this);
            dto.IsNew = (entry?.State == EntityState.Added);
            dto.IsDeleted = (entry?.State == EntityState.Deleted);

            if (entry?.Reference(x => x.Employer)?.IsLoaded == true)
            {
                dto.Employer = Employer?.ToDtoDeep(dbContext, entityDtos: entityDtos);
            }
            if (entry?.Reference(x => x.Form)?.IsLoaded == true)
            {
                dto.Form = Form?.ToDtoDeep(dbContext, entityDtos: entityDtos);
            }
            if (entry?.Collection(x => x.VoluntaryPlanWaiverRequestTypes)?.IsLoaded == true)
            {
                foreach (VoluntaryPlanWaiverRequestType voluntaryPlanWaiverRequestType in VoluntaryPlanWaiverRequestTypes)
                {
                    dto.VoluntaryPlanWaiverRequestTypes.Add(voluntaryPlanWaiverRequestType.ToDtoDeep(dbContext, entityDtos: entityDtos));
                }
            }

            return dto;
        }

        /// <summary>Convert from VoluntaryPlanWaiverRequest entity to DTO w/o checking entity state or entity navigation</summary>
        /// <param name="dto">DTO to use if already created instead of creating new one (can be inherited class instead as opposed to base class)</param>
        /// <returns>Resultant VoluntaryPlanWaiverRequest DTO</returns>
        public VoluntaryPlanWaiverRequestDto ToDto(VoluntaryPlanWaiverRequestDto dto = null)
        {

            dto = dto ?? new VoluntaryPlanWaiverRequestDto();
            dto.IsNew = false;

            dto.CreateDateTime = CreateDateTime;
            dto.CreateUserId = CreateUserId;
            dto.EmployerId = EmployerId;
            dto.EndDate = EndDate;
            dto.FormId = FormId;
            dto.IsVoluntaryPlanWaiverRequestAcknowledged = IsVoluntaryPlanWaiverRequestAcknowledged;
            dto.StartDate = StartDate;
            dto.UpdateDateTime = UpdateDateTime;
            dto.UpdateNumber = UpdateNumber;
            dto.UpdateProcess = UpdateProcess;
            dto.UpdateUserId = UpdateUserId;

            return dto;
        }

        /// <summary>Convert from VoluntaryPlanWaiverRequest DTO to entity</summary>
        /// <param name="dbContext">DB Context to use for attaching entity</param>
        /// <param name="dto">DTO to convert from</param>
        /// <param name="dtoEntities">Used internally to track which dtos have been converted to entites already (to avoid re-converting when circularly referenced)</param>
        /// <returns>Resultant VoluntaryPlanWaiverRequest entity</returns>
        public static VoluntaryPlanWaiverRequest FromDto(FACTS.Framework.DAL.DbContext dbContext, VoluntaryPlanWaiverRequestDto dto, Dictionary<FACTS.Framework.Dto.BaseDto, BaseEntity> dtoEntities = null)
        {
            dtoEntities = dtoEntities ?? new Dictionary<FACTS.Framework.Dto.BaseDto, BaseEntity>();
            if (dtoEntities.ContainsKey(dto))
            {
                return (VoluntaryPlanWaiverRequest)dtoEntities[dto];
            }

            VoluntaryPlanWaiverRequest entity = new VoluntaryPlanWaiverRequest();
            dtoEntities.Add(dto, entity);

            entity.CreateDateTime = dto.CreateDateTime;
            entity.CreateUserId = dto.CreateUserId;
            entity.EmployerId = dto.EmployerId;
            entity.EndDate = dto.EndDate;
            entity.FormId = dto.FormId;
            entity.IsVoluntaryPlanWaiverRequestAcknowledged = dto.IsVoluntaryPlanWaiverRequestAcknowledged;
            entity.StartDate = dto.StartDate;
            entity.UpdateDateTime = dto.UpdateDateTime;
            entity.UpdateNumber = dto.UpdateNumber;
            entity.UpdateProcess = dto.UpdateProcess;
            entity.UpdateUserId = dto.UpdateUserId;

            entity.Employer = (dto.Employer == null) ? null : Employer.FromDto(dbContext, dto.Employer, dtoEntities);
            entity.Form = (dto.Form == null) ? null : Form.FromDto(dbContext, dto.Form, dtoEntities);
            if (dto.VoluntaryPlanWaiverRequestTypes != null)
            {
                foreach (VoluntaryPlanWaiverRequestTypeDto voluntaryPlanWaiverRequestType in dto.VoluntaryPlanWaiverRequestTypes)
                {
                    entity.VoluntaryPlanWaiverRequestTypes.Add(DbEntities.VoluntaryPlanWaiverRequestType.FromDto(dbContext, voluntaryPlanWaiverRequestType, dtoEntities));
                }
            }

            if (dbContext != null)
            {
                dbContext.Entry(entity).State = (dto.IsNew ? EntityState.Added : (dto.IsDeleted ? EntityState.Deleted : EntityState.Modified));
            }

            return entity;
        }

    }

    /// <summary>Extension methods related to VoluntaryPlanWaiverRequest entity</summary>
    public static class VoluntaryPlanWaiverRequestExtension
    {

        /// <summary>Convert IEnumerable VoluntaryPlanWaiverRequest to list of DTOs</summary>
        /// <param name="entities">IEnumerable VoluntaryPlanWaiverRequests</param>
        /// <param name="dbContext">DB Context to use for setting state of DTO</param>
        /// <returns>List of DTO VoluntaryPlanWaiverRequests</returns>
        public static List<VoluntaryPlanWaiverRequestDto> ToDtoListDeep(this IEnumerable<VoluntaryPlanWaiverRequest> entities, FACTS.Framework.DAL.DbContext dbContext)
        {
            Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto> entityDtos = new Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto>();
            List<VoluntaryPlanWaiverRequestDto> dtos = new List<VoluntaryPlanWaiverRequestDto>();
            foreach (VoluntaryPlanWaiverRequest entity in entities)
            {
                dtos.Add(entity.ToDtoDeep(dbContext, entityDtos: entityDtos));
            }
            return dtos;
        }

        /// <summary>Convert L2E VoluntaryPlanWaiverRequest to list of DTOs</summary>
        /// <param name="entities">L2E VoluntaryPlanWaiverRequests</param>
        /// <param name="dbContext">DB Context to use for setting state of DTO</param>
        /// <returns>List of DTO VoluntaryPlanWaiverRequests</returns>
        public static List<VoluntaryPlanWaiverRequestDto> ToDtoListDeep(this IQueryable<VoluntaryPlanWaiverRequest> entities, FACTS.Framework.DAL.DbContext dbContext)
        {
            Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto> entityDtos = new Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto>();
            List<VoluntaryPlanWaiverRequestDto> dtos = new List<VoluntaryPlanWaiverRequestDto>();
            foreach (VoluntaryPlanWaiverRequest entity in entities)
            {
                dtos.Add(entity.ToDtoDeep(dbContext, entityDtos: entityDtos));
            }
            return dtos;
        }

        /// <summary>Convert L2E VoluntaryPlanWaiverRequest to list of customized DTOs</summary>
        /// <typeparam name="T">Custom DTO derived from VoluntaryPlanWaiverRequestDto</typeparam>
        /// <param name="entities">L2E VoluntaryPlanWaiverRequests</param>
        /// <param name="dbContext">DB Context to use for setting state of DTO</param>
        /// <returns>List of DTO customized VoluntaryPlanWaiverRequests</returns>
        public static List<T> ToDtoListDeep<T>(this IQueryable<VoluntaryPlanWaiverRequest> entities, FACTS.Framework.DAL.DbContext dbContext) where T : VoluntaryPlanWaiverRequestDto, new()
        {
            Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto> entityDtos = new Dictionary<BaseEntity, FACTS.Framework.Dto.BaseDto>();
            List<T> dtos = new List<T>();
            foreach (VoluntaryPlanWaiverRequest entity in entities)
            {
                dtos.Add((T)entity.ToDtoDeep(dbContext, new T(), entityDtos));
            }
            return dtos;
        }

        /// <summary>Convert IEnumerable VoluntaryPlanWaiverRequest to list of DTOs w/o checking entity state or entity navigation</summary>
        /// <param name="entities">IEnumerable VoluntaryPlanWaiverRequests</param>
        /// <returns>List of DTO VoluntaryPlanWaiverRequests</returns>
        public static List<VoluntaryPlanWaiverRequestDto> ToDtoList(this IEnumerable<VoluntaryPlanWaiverRequest> entities)
        {
            List<VoluntaryPlanWaiverRequestDto> dtos = new List<VoluntaryPlanWaiverRequestDto>();
            foreach (VoluntaryPlanWaiverRequest entity in entities)
            {
                dtos.Add(entity.ToDto());
            }
            return dtos;
        }

        /// <summary>Convert L2E VoluntaryPlanWaiverRequest to list of DTOs w/o checking entity state or entity navigation</summary>
        /// <param name="entities">L2E VoluntaryPlanWaiverRequests</param>
        /// <returns>List of DTO VoluntaryPlanWaiverRequests</returns>
        public static List<VoluntaryPlanWaiverRequestDto> ToDtoList(this IQueryable<VoluntaryPlanWaiverRequest> entities)
        {
            List<VoluntaryPlanWaiverRequestDto> dtos = new List<VoluntaryPlanWaiverRequestDto>();
            foreach (VoluntaryPlanWaiverRequest entity in entities)
            {
                dtos.Add(entity.ToDto());
            }
            return dtos;
        }

        /// <summary>Convert L2E VoluntaryPlanWaiverRequest to list of customized DTOs w/o checking entity state or entity navigation</summary>
        /// <typeparam name="T">Custom DTO derived from VoluntaryPlanWaiverRequestDto</typeparam>
        /// <param name="entities">L2E VoluntaryPlanWaiverRequests</param>
        /// <returns>List of DTO customized VoluntaryPlanWaiverRequests</returns>
        public static List<T> ToDtoList<T>(this IQueryable<VoluntaryPlanWaiverRequest> entities) where T : VoluntaryPlanWaiverRequestDto, new()
        {
            List<T> dtos = new List<T>();
            foreach (VoluntaryPlanWaiverRequest entity in entities)
            {
                dtos.Add((T)entity.ToDto(new T()));
            }
            return dtos;
        }

    }

}
