// ----------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a compiler emitter: FACTS.Framework.Analysis.Generators.LookupTable.Emitter
//
// Changes to this file may cause incorrect behavior and will be lost when the code is regenerated.
// </auto-generated>
// ----------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PFML.Shared.LookupTable
{

    /// <summary>Table of lookup names</summary>
    public static class LookupTable
    {
        /// <summary>Lookup name: SecurityPermissionType</summary>
        public const string SecurityPermissionType = "SecurityPermissionType";
        /// <summary>Lookup name: SecurityAccess</summary>
        public const string SecurityAccess = "SecurityAccess";
        /// <summary>Lookup name: AddressType</summary>
        public const string AddressType = "AddressType";
        /// <summary>Lookup name: BankAccountType</summary>
        public const string BankAccountType = "BankAccountType";
        /// <summary>Lookup name: BoolConversion</summary>
        public const string BoolConversion = "BoolConversion";
        /// <summary>Lookup name: BoolYesNo</summary>
        public const string BoolYesNo = "BoolYesNo";
        /// <summary>Lookup name: BoolYesNoNA</summary>
        public const string BoolYesNoNA = "BoolYesNoNA";
        /// <summary>Lookup name: BusinessType</summary>
        public const string BusinessType = "BusinessType";
        /// <summary>Lookup name: CommunicationMethod</summary>
        public const string CommunicationMethod = "CommunicationMethod";
        /// <summary>Lookup name: ContactType</summary>
        public const string ContactType = "ContactType";
        /// <summary>Lookup name: Country</summary>
        public const string Country = "Country";
        /// <summary>Lookup name: County</summary>
        public const string County = "County";
        /// <summary>Lookup name: EmployerReportMethod</summary>
        public const string EmployerReportMethod = "EmployerReportMethod";
        /// <summary>Lookup name: EmployerStatus</summary>
        public const string EmployerStatus = "EmployerStatus";
        /// <summary>Lookup name: FormType</summary>
        public const string FormType = "FormType";
        /// <summary>Lookup name: LegalEntity</summary>
        public const string LegalEntity = "LegalEntity";
        /// <summary>Lookup name: MakePaymentWizardFlow</summary>
        public const string MakePaymentWizardFlow = "MakePaymentWizardFlow";
        /// <summary>Lookup name: MaritalStatus</summary>
        public const string MaritalStatus = "MaritalStatus";
        /// <summary>Lookup name: PaymentMethodType</summary>
        public const string PaymentMethodType = "PaymentMethodType";
        /// <summary>Lookup name: PaymentStatus</summary>
        public const string PaymentStatus = "PaymentStatus";
        /// <summary>Lookup name: PersonGender</summary>
        public const string PersonGender = "PersonGender";
        /// <summary>Lookup name: PersonStatus</summary>
        public const string PersonStatus = "PersonStatus";
        /// <summary>Lookup name: PreferredCommunicationMethod</summary>
        public const string PreferredCommunicationMethod = "PreferredCommunicationMethod";
        /// <summary>Lookup name: Prefix</summary>
        public const string Prefix = "Prefix";
        /// <summary>Lookup name: PremiumPaymentDueDays</summary>
        public const string PremiumPaymentDueDays = "PremiumPaymentDueDays";
        /// <summary>Lookup name: Quarter</summary>
        public const string Quarter = "Quarter";
        /// <summary>Lookup name: State</summary>
        public const string State = "State";
        /// <summary>Lookup name: StatePrvnc</summary>
        public const string StatePrvnc = "StatePrvnc";
        /// <summary>Lookup name: Suffix</summary>
        public const string Suffix = "Suffix";
        /// <summary>Lookup name: TaxableAmSumStatus</summary>
        public const string TaxableAmSumStatus = "TaxableAmSumStatus";
        /// <summary>Lookup name: TransactionType</summary>
        public const string TransactionType = "TransactionType";
        /// <summary>Lookup name: ValidationType</summary>
        public const string ValidationType = "ValidationType";
        /// <summary>Lookup name: WageDetailAdjReasonCode</summary>
        public const string WageDetailAdjReasonCode = "WageDetailAdjReasonCode";
        /// <summary>Lookup name: WageDetailFilingMethod</summary>
        public const string WageDetailFilingMethod = "WageDetailFilingMethod";
        /// <summary>Lookup name: WageDetailUnitYears</summary>
        public const string WageDetailUnitYears = "WageDetailUnitYears";
        /// <summary>Lookup name: WaiverLeaveType</summary>
        public const string WaiverLeaveType = "WaiverLeaveType";
        /// <summary>Lookup name: WaiverRequestStatus</summary>
        public const string WaiverRequestStatus = "WaiverRequestStatus";
        /// <summary>Lookup name: WaiverWeeksAvailable</summary>
        public const string WaiverWeeksAvailable = "WaiverWeeksAvailable";
        /// <summary>Lookup name: WizEmployerRegistration</summary>
        public const string WizEmployerRegistration = "WizEmployerRegistration";
        /// <summary>Lookup name: WizEmployerWageFiling</summary>
        public const string WizEmployerWageFiling = "WizEmployerWageFiling";
    }

    /// <summary>Table of lookup codes for: SecurityPermissionType
    public static class LookupTable_SecurityPermissionType
    {
        /// <summary>Lookup code: USER</summary>
        public const string User = "USER";
        /// <summary>Lookup code: GROUP</summary>
        public const string Group = "GROUP";
        /// <summary>Lookup code: ROLE</summary>
        public const string Role = "ROLE";
        /// <summary>Lookup code: OBJECT</summary>
        public const string Object = "OBJECT";
    }

    /// <summary>Table of lookup properties for: SecurityPermissionType
    public static class LookupTable_SecurityPermissionType_Properties
    {
    }

    /// <summary>Table of lookup codes for: SecurityAccess
    public static class LookupTable_SecurityAccess
    {
        /// <summary>Lookup code: NONE</summary>
        public const string None = "NONE";
        /// <summary>Lookup code: READ</summary>
        public const string Read = "READ";
        /// <summary>Lookup code: FULL</summary>
        public const string Full = "FULL";
    }

    /// <summary>Table of lookup properties for: SecurityAccess
    public static class LookupTable_SecurityAccess_Properties
    {
    }

    /// <summary>Table of lookup codes for: AddressType
    public static class LookupTable_AddressType
    {
        /// <summary>Lookup code: BUSI</summary>
        public const string Business = "BUSI";
        /// <summary>Lookup code: MAIL</summary>
        public const string Mailing = "MAIL";
        /// <summary>Lookup code: PHYS</summary>
        public const string Physical = "PHYS";
    }

    /// <summary>Table of lookup properties for: AddressType
    public static class LookupTable_AddressType_Properties
    {
        /// <summary>Lookup property: DisplaySortOrder : To manipulate sort order</summary>
        public const string DisplaySortOrder = "DisplaySortOrder";
    }

    /// <summary>Table of lookup codes for: BankAccountType
    public static class LookupTable_BankAccountType
    {
        /// <summary>Lookup code: CHEK</summary>
        public const string Checking = "CHEK";
        /// <summary>Lookup code: SAVN</summary>
        public const string Savings = "SAVN";
    }

    /// <summary>Table of lookup properties for: BankAccountType
    public static class LookupTable_BankAccountType_Properties
    {
    }

    /// <summary>Table of lookup codes for: BoolConversion
    public static class LookupTable_BoolConversion
    {
        /// <summary>Lookup code: False</summary>
        public const string No = "False";
        /// <summary>Lookup code: True</summary>
        public const string Yes = "True";
    }

    /// <summary>Table of lookup properties for: BoolConversion
    public static class LookupTable_BoolConversion_Properties
    {
        /// <summary>Lookup property: DisplaySortOrder : To manipulate sort order</summary>
        public const string DisplaySortOrder = "DisplaySortOrder";
    }

    /// <summary>Table of lookup codes for: BoolYesNo
    public static class LookupTable_BoolYesNo
    {
        /// <summary>Lookup code: N</summary>
        public const string No = "N";
        /// <summary>Lookup code: Y</summary>
        public const string Yes = "Y";
    }

    /// <summary>Table of lookup properties for: BoolYesNo
    public static class LookupTable_BoolYesNo_Properties
    {
        /// <summary>Lookup property: DisplaySortOrder : To manipulate sort order</summary>
        public const string DisplaySortOrder = "DisplaySortOrder";
    }

    /// <summary>Table of lookup codes for: BoolYesNoNA
    public static class LookupTable_BoolYesNoNA
    {
        /// <summary>Lookup code: N</summary>
        public const string No = "N";
        /// <summary>Lookup code: NA</summary>
        public const string No_2 = "NA";
        /// <summary>Lookup code: Y</summary>
        public const string Yes = "Y";
    }

    /// <summary>Table of lookup properties for: BoolYesNoNA
    public static class LookupTable_BoolYesNoNA_Properties
    {
        /// <summary>Lookup property: DisplaySortOrder : To manipulate sort order</summary>
        public const string DisplaySortOrder = "DisplaySortOrder";
    }

    /// <summary>Table of lookup codes for: BusinessType
    public static class LookupTable_BusinessType
    {
        /// <summary>Lookup code: AGRE</summary>
        public const string Agricultural = "AGRE";
        /// <summary>Lookup code: DOME</summary>
        public const string Domestic = "DOME";
        /// <summary>Lookup code: NAGR</summary>
        public const string NonAgriculturalRegularEmployment = "NAGR";
    }

    /// <summary>Table of lookup properties for: BusinessType
    public static class LookupTable_BusinessType_Properties
    {
        /// <summary>Lookup property: DisplaySortOrder : To manipulate sort order</summary>
        public const string DisplaySortOrder = "DisplaySortOrder";
    }

    /// <summary>Table of lookup codes for: CommunicationMethod
    public static class LookupTable_CommunicationMethod
    {
        /// <summary>Lookup code: ELEC</summary>
        public const string Email = "ELEC";
        /// <summary>Lookup code: PAPR</summary>
        public const string USMail = "PAPR";
    }

    /// <summary>Table of lookup properties for: CommunicationMethod
    public static class LookupTable_CommunicationMethod_Properties
    {
        /// <summary>Lookup property: DisplaySortOrder : To manipulate sort order</summary>
        public const string DisplaySortOrder = "DisplaySortOrder";
    }

    /// <summary>Table of lookup codes for: ContactType
    public static class LookupTable_ContactType
    {
        /// <summary>Lookup code: ADMN</summary>
        public const string Administrator = "ADMN";
        /// <summary>Lookup code: CNTP</summary>
        public const string ContactPerson = "CNTP";
    }

    /// <summary>Table of lookup properties for: ContactType
    public static class LookupTable_ContactType_Properties
    {
    }

    /// <summary>Table of lookup codes for: Country
    public static class LookupTable_Country
    {
        /// <summary>Lookup code: AD</summary>
        public const string Andorra = "AD";
        /// <summary>Lookup code: AE</summary>
        public const string UnitedArabEmirates = "AE";
        /// <summary>Lookup code: AF</summary>
        public const string Afghanistan = "AF";
        /// <summary>Lookup code: AG</summary>
        public const string AntiguaAndBarbuda = "AG";
        /// <summary>Lookup code: AI</summary>
        public const string Anguilla = "AI";
        /// <summary>Lookup code: AL</summary>
        public const string Albania = "AL";
        /// <summary>Lookup code: AM</summary>
        public const string Armenia = "AM";
        /// <summary>Lookup code: AN</summary>
        public const string NetherlandsAntilles = "AN";
        /// <summary>Lookup code: AO</summary>
        public const string Angola = "AO";
        /// <summary>Lookup code: AQ</summary>
        public const string Antarctica = "AQ";
        /// <summary>Lookup code: AR</summary>
        public const string Argentina = "AR";
        /// <summary>Lookup code: AS</summary>
        public const string AmericanSamoa = "AS";
        /// <summary>Lookup code: AT</summary>
        public const string Austria = "AT";
        /// <summary>Lookup code: AU</summary>
        public const string Australia = "AU";
        /// <summary>Lookup code: AW</summary>
        public const string Aruba = "AW";
        /// <summary>Lookup code: AX</summary>
        public const string AlandIslands = "AX";
        /// <summary>Lookup code: AZ</summary>
        public const string Azerbaijan = "AZ";
        /// <summary>Lookup code: BA</summary>
        public const string BosniaAndHerzegovina = "BA";
        /// <summary>Lookup code: BB</summary>
        public const string Barbados = "BB";
        /// <summary>Lookup code: BD</summary>
        public const string Bangladesh = "BD";
        /// <summary>Lookup code: BE</summary>
        public const string Belgium = "BE";
        /// <summary>Lookup code: BF</summary>
        public const string BurkinaFaso = "BF";
        /// <summary>Lookup code: BG</summary>
        public const string Bulgaria = "BG";
        /// <summary>Lookup code: BH</summary>
        public const string Bahrain = "BH";
        /// <summary>Lookup code: BI</summary>
        public const string Burundi = "BI";
        /// <summary>Lookup code: BJ</summary>
        public const string Benin = "BJ";
        /// <summary>Lookup code: BM</summary>
        public const string Bermuda = "BM";
        /// <summary>Lookup code: BN</summary>
        public const string BruneiDarussalam = "BN";
        /// <summary>Lookup code: BO</summary>
        public const string Bolivia = "BO";
        /// <summary>Lookup code: BR</summary>
        public const string Brazil = "BR";
        /// <summary>Lookup code: BS</summary>
        public const string Bahamas = "BS";
        /// <summary>Lookup code: BT</summary>
        public const string Bhutan = "BT";
        /// <summary>Lookup code: BV</summary>
        public const string BouvetIsland = "BV";
        /// <summary>Lookup code: BW</summary>
        public const string Botswana = "BW";
        /// <summary>Lookup code: BY</summary>
        public const string Belarus = "BY";
        /// <summary>Lookup code: BZ</summary>
        public const string Belize = "BZ";
        /// <summary>Lookup code: CA</summary>
        public const string Canada = "CA";
        /// <summary>Lookup code: CAAB</summary>
        public const string CanadaAlberta = "CAAB";
        /// <summary>Lookup code: CABC</summary>
        public const string CanadaBritishColumbia = "CABC";
        /// <summary>Lookup code: CALB</summary>
        public const string CanadaLabrador = "CALB";
        /// <summary>Lookup code: CAMB</summary>
        public const string CanadaManitoba = "CAMB";
        /// <summary>Lookup code: CANB</summary>
        public const string CanadaNewBrunswick = "CANB";
        /// <summary>Lookup code: CANL</summary>
        public const string CanadaNewfoundland = "CANL";
        /// <summary>Lookup code: CANS</summary>
        public const string CanadaNovaScotia = "CANS";
        /// <summary>Lookup code: CANT</summary>
        public const string CanadaNorthwestTerritories = "CANT";
        /// <summary>Lookup code: CANU</summary>
        public const string CanadaNunavut = "CANU";
        /// <summary>Lookup code: CAON</summary>
        public const string CanadaOntario = "CAON";
        /// <summary>Lookup code: CAPE</summary>
        public const string CanadaPrinceEdwardIsland = "CAPE";
        /// <summary>Lookup code: CAQC</summary>
        public const string CanadaQuebec = "CAQC";
        /// <summary>Lookup code: CASK</summary>
        public const string CanadaSaskatchewan = "CASK";
        /// <summary>Lookup code: CAYT</summary>
        public const string CanadaYukonTerritory = "CAYT";
        /// <summary>Lookup code: CC</summary>
        public const string CocosKeelingIslands = "CC";
        /// <summary>Lookup code: CD</summary>
        public const string CongoTheDemocraticRepublicOfThe = "CD";
        /// <summary>Lookup code: CF</summary>
        public const string CentralAfricanRepublic = "CF";
        /// <summary>Lookup code: CG</summary>
        public const string Congo = "CG";
        /// <summary>Lookup code: CH</summary>
        public const string Switzerland = "CH";
        /// <summary>Lookup code: CI</summary>
        public const string CoteDivoire = "CI";
        /// <summary>Lookup code: CK</summary>
        public const string CookIslands = "CK";
        /// <summary>Lookup code: CL</summary>
        public const string Chile = "CL";
        /// <summary>Lookup code: CM</summary>
        public const string Cameroon = "CM";
        /// <summary>Lookup code: CN</summary>
        public const string China = "CN";
        /// <summary>Lookup code: CO</summary>
        public const string Colombia = "CO";
        /// <summary>Lookup code: CR</summary>
        public const string CostaRica = "CR";
        /// <summary>Lookup code: CS</summary>
        public const string SerbiaAndMontenegro = "CS";
        /// <summary>Lookup code: CU</summary>
        public const string Cuba = "CU";
        /// <summary>Lookup code: CV</summary>
        public const string CapeVerde = "CV";
        /// <summary>Lookup code: CX</summary>
        public const string ChristmasIsland = "CX";
        /// <summary>Lookup code: CY</summary>
        public const string Cyprus = "CY";
        /// <summary>Lookup code: CZ</summary>
        public const string CzechRepublic = "CZ";
        /// <summary>Lookup code: DE</summary>
        public const string Germany = "DE";
        /// <summary>Lookup code: DJ</summary>
        public const string Djibouti = "DJ";
        /// <summary>Lookup code: DK</summary>
        public const string Denmark = "DK";
        /// <summary>Lookup code: DM</summary>
        public const string Dominica = "DM";
        /// <summary>Lookup code: DO</summary>
        public const string DominicanRepublic = "DO";
        /// <summary>Lookup code: DZ</summary>
        public const string Algeria = "DZ";
        /// <summary>Lookup code: EC</summary>
        public const string Ecuador = "EC";
        /// <summary>Lookup code: EE</summary>
        public const string Estonia = "EE";
        /// <summary>Lookup code: EG</summary>
        public const string Egypt = "EG";
        /// <summary>Lookup code: EH</summary>
        public const string WesternSahara = "EH";
        /// <summary>Lookup code: ER</summary>
        public const string Eritrea = "ER";
        /// <summary>Lookup code: ES</summary>
        public const string Spain = "ES";
        /// <summary>Lookup code: ET</summary>
        public const string Ethiopia = "ET";
        /// <summary>Lookup code: FI</summary>
        public const string Finland = "FI";
        /// <summary>Lookup code: FJ</summary>
        public const string Fiji = "FJ";
        /// <summary>Lookup code: FK</summary>
        public const string FalklandIslandsMalvinas = "FK";
        /// <summary>Lookup code: FM</summary>
        public const string MicronesiaFederatedStatesOf = "FM";
        /// <summary>Lookup code: FO</summary>
        public const string FaroeIslands = "FO";
        /// <summary>Lookup code: FR</summary>
        public const string France = "FR";
        /// <summary>Lookup code: GA</summary>
        public const string Gabon = "GA";
        /// <summary>Lookup code: GB</summary>
        public const string UnitedKingdom = "GB";
        /// <summary>Lookup code: GD</summary>
        public const string Grenada = "GD";
        /// <summary>Lookup code: GE</summary>
        public const string Georgia = "GE";
        /// <summary>Lookup code: GF</summary>
        public const string FrenchGuiana = "GF";
        /// <summary>Lookup code: GH</summary>
        public const string Ghana = "GH";
        /// <summary>Lookup code: GI</summary>
        public const string Gibraltar = "GI";
        /// <summary>Lookup code: GL</summary>
        public const string Greenland = "GL";
        /// <summary>Lookup code: GM</summary>
        public const string Gambia = "GM";
        /// <summary>Lookup code: GN</summary>
        public const string Guinea = "GN";
        /// <summary>Lookup code: GP</summary>
        public const string Guadeloupe = "GP";
        /// <summary>Lookup code: GQ</summary>
        public const string EquatorialGuinea = "GQ";
        /// <summary>Lookup code: GR</summary>
        public const string Greece = "GR";
        /// <summary>Lookup code: GS</summary>
        public const string SouthGeorgiaAndTheSouthSandwichIsland = "GS";
        /// <summary>Lookup code: GT</summary>
        public const string Guatemala = "GT";
        /// <summary>Lookup code: GU</summary>
        public const string Guam = "GU";
        /// <summary>Lookup code: GW</summary>
        public const string GuineaBissau = "GW";
        /// <summary>Lookup code: GY</summary>
        public const string Guyana = "GY";
        /// <summary>Lookup code: HK</summary>
        public const string HongKong = "HK";
        /// <summary>Lookup code: HM</summary>
        public const string HeardIslandAndMcdonaldIslands = "HM";
        /// <summary>Lookup code: HN</summary>
        public const string Honduras = "HN";
        /// <summary>Lookup code: HR</summary>
        public const string Croatia = "HR";
        /// <summary>Lookup code: HT</summary>
        public const string Haiti = "HT";
        /// <summary>Lookup code: HU</summary>
        public const string Hungary = "HU";
        /// <summary>Lookup code: ID</summary>
        public const string Indonesia = "ID";
        /// <summary>Lookup code: IE</summary>
        public const string Ireland = "IE";
        /// <summary>Lookup code: IL</summary>
        public const string Israel = "IL";
        /// <summary>Lookup code: IN</summary>
        public const string India = "IN";
        /// <summary>Lookup code: IO</summary>
        public const string BritishIndianOceanTerritory = "IO";
        /// <summary>Lookup code: IQ</summary>
        public const string Iraq = "IQ";
        /// <summary>Lookup code: IR</summary>
        public const string IranIslamicRepublicOf = "IR";
        /// <summary>Lookup code: IS</summary>
        public const string Iceland = "IS";
        /// <summary>Lookup code: IT</summary>
        public const string Italy = "IT";
        /// <summary>Lookup code: JM</summary>
        public const string Jamaica = "JM";
        /// <summary>Lookup code: JO</summary>
        public const string Jordan = "JO";
        /// <summary>Lookup code: JP</summary>
        public const string Japan = "JP";
        /// <summary>Lookup code: KE</summary>
        public const string Kenya = "KE";
        /// <summary>Lookup code: KG</summary>
        public const string Kyrgyzstan = "KG";
        /// <summary>Lookup code: KH</summary>
        public const string Cambodia = "KH";
        /// <summary>Lookup code: KI</summary>
        public const string Kiribati = "KI";
        /// <summary>Lookup code: KM</summary>
        public const string Comoros = "KM";
        /// <summary>Lookup code: KN</summary>
        public const string SaintKittsAndNevis = "KN";
        /// <summary>Lookup code: KP</summary>
        public const string KoreaDemocraticPeoplesRepublicOf = "KP";
        /// <summary>Lookup code: KR</summary>
        public const string KoreaRepublicOf = "KR";
        /// <summary>Lookup code: KW</summary>
        public const string Kuwait = "KW";
        /// <summary>Lookup code: KY</summary>
        public const string CaymanIslands = "KY";
        /// <summary>Lookup code: KZ</summary>
        public const string Kazakhstan = "KZ";
        /// <summary>Lookup code: LA</summary>
        public const string LaoPeoplesDemocraticRepublic = "LA";
        /// <summary>Lookup code: LB</summary>
        public const string Lebanon = "LB";
        /// <summary>Lookup code: LC</summary>
        public const string SaintLucia = "LC";
        /// <summary>Lookup code: LI</summary>
        public const string Liechtenstein = "LI";
        /// <summary>Lookup code: LK</summary>
        public const string SriLanka = "LK";
        /// <summary>Lookup code: LR</summary>
        public const string Liberia = "LR";
        /// <summary>Lookup code: LS</summary>
        public const string Lesotho = "LS";
        /// <summary>Lookup code: LT</summary>
        public const string Lithuania = "LT";
        /// <summary>Lookup code: LU</summary>
        public const string Luxembourg = "LU";
        /// <summary>Lookup code: LV</summary>
        public const string Latvia = "LV";
        /// <summary>Lookup code: LY</summary>
        public const string LibyanArabJamahiriya = "LY";
        /// <summary>Lookup code: MA</summary>
        public const string Morocco = "MA";
        /// <summary>Lookup code: MC</summary>
        public const string Monaco = "MC";
        /// <summary>Lookup code: MD</summary>
        public const string MoldovaRepublicOf = "MD";
        /// <summary>Lookup code: MG</summary>
        public const string Madagascar = "MG";
        /// <summary>Lookup code: MH</summary>
        public const string MarshallIslands = "MH";
        /// <summary>Lookup code: MK</summary>
        public const string MacedoniaTheFormerYugoslavRepublicOf = "MK";
        /// <summary>Lookup code: ML</summary>
        public const string Mali = "ML";
        /// <summary>Lookup code: MM</summary>
        public const string Myanmar = "MM";
        /// <summary>Lookup code: MN</summary>
        public const string Mongolia = "MN";
        /// <summary>Lookup code: MO</summary>
        public const string Macao = "MO";
        /// <summary>Lookup code: MP</summary>
        public const string NorthernMarianaIslands = "MP";
        /// <summary>Lookup code: MQ</summary>
        public const string Martinique = "MQ";
        /// <summary>Lookup code: MR</summary>
        public const string Mauritania = "MR";
        /// <summary>Lookup code: MS</summary>
        public const string Montserrat = "MS";
        /// <summary>Lookup code: MT</summary>
        public const string Malta = "MT";
        /// <summary>Lookup code: MU</summary>
        public const string Mauritius = "MU";
        /// <summary>Lookup code: MV</summary>
        public const string Maldives = "MV";
        /// <summary>Lookup code: MW</summary>
        public const string Malawi = "MW";
        /// <summary>Lookup code: MX</summary>
        public const string Mexico = "MX";
        /// <summary>Lookup code: MY</summary>
        public const string Malaysia = "MY";
        /// <summary>Lookup code: MZ</summary>
        public const string Mozambique = "MZ";
        /// <summary>Lookup code: NA</summary>
        public const string Namibia = "NA";
        /// <summary>Lookup code: NC</summary>
        public const string NewCaledonia = "NC";
        /// <summary>Lookup code: NE</summary>
        public const string Niger = "NE";
        /// <summary>Lookup code: NF</summary>
        public const string NorfolkIsland = "NF";
        /// <summary>Lookup code: NG</summary>
        public const string Nigeria = "NG";
        /// <summary>Lookup code: NI</summary>
        public const string Nicaragua = "NI";
        /// <summary>Lookup code: NL</summary>
        public const string Netherlands = "NL";
        /// <summary>Lookup code: NO</summary>
        public const string Norway = "NO";
        /// <summary>Lookup code: NP</summary>
        public const string Nepal = "NP";
        /// <summary>Lookup code: NR</summary>
        public const string Nauru = "NR";
        /// <summary>Lookup code: NU</summary>
        public const string Niue = "NU";
        /// <summary>Lookup code: NZ</summary>
        public const string NewZealand = "NZ";
        /// <summary>Lookup code: OM</summary>
        public const string Oman = "OM";
        /// <summary>Lookup code: PA</summary>
        public const string Panama = "PA";
        /// <summary>Lookup code: PE</summary>
        public const string Peru = "PE";
        /// <summary>Lookup code: PF</summary>
        public const string FrenchPolynesia = "PF";
        /// <summary>Lookup code: PG</summary>
        public const string PapuaNewGuinea = "PG";
        /// <summary>Lookup code: PH</summary>
        public const string Philippines = "PH";
        /// <summary>Lookup code: PK</summary>
        public const string Pakistan = "PK";
        /// <summary>Lookup code: PL</summary>
        public const string Poland = "PL";
        /// <summary>Lookup code: PM</summary>
        public const string SaintPierreAndMiquelon = "PM";
        /// <summary>Lookup code: PN</summary>
        public const string Pitcairn = "PN";
        /// <summary>Lookup code: PR</summary>
        public const string PuertoRico = "PR";
        /// <summary>Lookup code: PS</summary>
        public const string PalestinianTerritoryOccupied = "PS";
        /// <summary>Lookup code: PT</summary>
        public const string Portugal = "PT";
        /// <summary>Lookup code: PW</summary>
        public const string Palau = "PW";
        /// <summary>Lookup code: PY</summary>
        public const string Paraguay = "PY";
        /// <summary>Lookup code: QA</summary>
        public const string Qatar = "QA";
        /// <summary>Lookup code: RE</summary>
        public const string Reunion = "RE";
        /// <summary>Lookup code: RO</summary>
        public const string Romania = "RO";
        /// <summary>Lookup code: RU</summary>
        public const string RussianFederation = "RU";
        /// <summary>Lookup code: RW</summary>
        public const string Rwanda = "RW";
        /// <summary>Lookup code: SA</summary>
        public const string SaudiArabia = "SA";
        /// <summary>Lookup code: SB</summary>
        public const string SolomonIslands = "SB";
        /// <summary>Lookup code: SC</summary>
        public const string Seychelles = "SC";
        /// <summary>Lookup code: SD</summary>
        public const string Sudan = "SD";
        /// <summary>Lookup code: SE</summary>
        public const string Sweden = "SE";
        /// <summary>Lookup code: SG</summary>
        public const string Singapore = "SG";
        /// <summary>Lookup code: SH</summary>
        public const string SaintHelena = "SH";
        /// <summary>Lookup code: SI</summary>
        public const string Slovenia = "SI";
        /// <summary>Lookup code: SJ</summary>
        public const string SvalbardAndJanMayen = "SJ";
        /// <summary>Lookup code: SK</summary>
        public const string Slovakia = "SK";
        /// <summary>Lookup code: SL</summary>
        public const string SierraLeone = "SL";
        /// <summary>Lookup code: SM</summary>
        public const string SanMarino = "SM";
        /// <summary>Lookup code: SN</summary>
        public const string Senegal = "SN";
        /// <summary>Lookup code: SO</summary>
        public const string Somalia = "SO";
        /// <summary>Lookup code: SR</summary>
        public const string Suriname = "SR";
        /// <summary>Lookup code: ST</summary>
        public const string SaoTomeAndPrincipe = "ST";
        /// <summary>Lookup code: SV</summary>
        public const string ElSalvador = "SV";
        /// <summary>Lookup code: SY</summary>
        public const string SyrianArabRepublic = "SY";
        /// <summary>Lookup code: SZ</summary>
        public const string Swaziland = "SZ";
        /// <summary>Lookup code: TC</summary>
        public const string TurksAndCaicosIslands = "TC";
        /// <summary>Lookup code: TD</summary>
        public const string Chad = "TD";
        /// <summary>Lookup code: TF</summary>
        public const string FrenchSouthernTerritories = "TF";
        /// <summary>Lookup code: TG</summary>
        public const string Togo = "TG";
        /// <summary>Lookup code: TH</summary>
        public const string Thailand = "TH";
        /// <summary>Lookup code: TJ</summary>
        public const string Tajikistan = "TJ";
        /// <summary>Lookup code: TK</summary>
        public const string Tokelau = "TK";
        /// <summary>Lookup code: TL</summary>
        public const string TimorLeste = "TL";
        /// <summary>Lookup code: TM</summary>
        public const string Turkmenistan = "TM";
        /// <summary>Lookup code: TN</summary>
        public const string Tunisia = "TN";
        /// <summary>Lookup code: TO</summary>
        public const string Tonga = "TO";
        /// <summary>Lookup code: TR</summary>
        public const string Turkey = "TR";
        /// <summary>Lookup code: TT</summary>
        public const string TrinidadAndTobago = "TT";
        /// <summary>Lookup code: TV</summary>
        public const string Tuvalu = "TV";
        /// <summary>Lookup code: TW</summary>
        public const string TaiwanProvinceOfChina = "TW";
        /// <summary>Lookup code: TZ</summary>
        public const string TanzaniaUnitedRepublicOf = "TZ";
        /// <summary>Lookup code: UA</summary>
        public const string Ukraine = "UA";
        /// <summary>Lookup code: UG</summary>
        public const string Uganda = "UG";
        /// <summary>Lookup code: UM</summary>
        public const string UnitedStatesMinorOutlyingIslands = "UM";
        /// <summary>Lookup code: US</summary>
        public const string UnitedStates = "US";
        /// <summary>Lookup code: USA</summary>
        public const string UnitedStates_2 = "USA";
        /// <summary>Lookup code: UY</summary>
        public const string Uruguay = "UY";
        /// <summary>Lookup code: UZ</summary>
        public const string Uzbekistan = "UZ";
        /// <summary>Lookup code: VA</summary>
        public const string HolySeeVaticanCityState = "VA";
        /// <summary>Lookup code: VC</summary>
        public const string SaintVincentAndTheGrenadines = "VC";
        /// <summary>Lookup code: VE</summary>
        public const string Venezuela = "VE";
        /// <summary>Lookup code: VG</summary>
        public const string VirginIslandsBritish = "VG";
        /// <summary>Lookup code: VI</summary>
        public const string VirginIslandsUS = "VI";
        /// <summary>Lookup code: VN</summary>
        public const string VietNam = "VN";
        /// <summary>Lookup code: VU</summary>
        public const string Vanuatu = "VU";
        /// <summary>Lookup code: WF</summary>
        public const string WallisAndFutuna = "WF";
        /// <summary>Lookup code: WS</summary>
        public const string Samoa = "WS";
        /// <summary>Lookup code: YE</summary>
        public const string Yemen = "YE";
        /// <summary>Lookup code: YT</summary>
        public const string Mayotte = "YT";
        /// <summary>Lookup code: ZA</summary>
        public const string SouthAfrica = "ZA";
        /// <summary>Lookup code: ZM</summary>
        public const string Zambia = "ZM";
        /// <summary>Lookup code: ZW</summary>
        public const string Zimbabwe = "ZW";
    }

    /// <summary>Table of lookup properties for: Country
    public static class LookupTable_Country_Properties
    {
        /// <summary>Lookup property: ISOCountryCode : The purpose of this column is to store the ISO country code values.</summary>
        public const string ISOCountryCode = "ISOCountryCode";
    }

    /// <summary>Table of lookup codes for: County
    public static class LookupTable_County
    {
        /// <summary>Lookup code: 000</summary>
        public const string OutofState = "000";
        /// <summary>Lookup code: 01</summary>
        public const string Alameda = "01";
        /// <summary>Lookup code: 02</summary>
        public const string Alpine = "02";
        /// <summary>Lookup code: 03</summary>
        public const string Amador = "03";
        /// <summary>Lookup code: 04</summary>
        public const string Butte = "04";
        /// <summary>Lookup code: 05</summary>
        public const string Calaveras = "05";
        /// <summary>Lookup code: 06</summary>
        public const string Colusa = "06";
        /// <summary>Lookup code: 07</summary>
        public const string ContraCosta = "07";
        /// <summary>Lookup code: 08</summary>
        public const string DelNorte = "08";
        /// <summary>Lookup code: 09</summary>
        public const string ElDorado = "09";
        /// <summary>Lookup code: 10</summary>
        public const string Fresno = "10";
        /// <summary>Lookup code: 11</summary>
        public const string Glenn = "11";
        /// <summary>Lookup code: 12</summary>
        public const string Humboldt = "12";
        /// <summary>Lookup code: 13</summary>
        public const string Imperial = "13";
        /// <summary>Lookup code: 14</summary>
        public const string Inyo = "14";
        /// <summary>Lookup code: 15</summary>
        public const string Kern = "15";
        /// <summary>Lookup code: 16</summary>
        public const string Kings = "16";
        /// <summary>Lookup code: 17</summary>
        public const string Lake = "17";
        /// <summary>Lookup code: 18</summary>
        public const string Lassen = "18";
        /// <summary>Lookup code: 19</summary>
        public const string LosAngeles = "19";
        /// <summary>Lookup code: 20</summary>
        public const string Madera = "20";
        /// <summary>Lookup code: 21</summary>
        public const string Marin = "21";
        /// <summary>Lookup code: 22</summary>
        public const string Mariposa = "22";
        /// <summary>Lookup code: 23</summary>
        public const string Mendocino = "23";
        /// <summary>Lookup code: 24</summary>
        public const string Merced = "24";
        /// <summary>Lookup code: 25</summary>
        public const string Modoc = "25";
        /// <summary>Lookup code: 26</summary>
        public const string Mono = "26";
        /// <summary>Lookup code: 27</summary>
        public const string Monterey = "27";
        /// <summary>Lookup code: 28</summary>
        public const string Napa = "28";
        /// <summary>Lookup code: 29</summary>
        public const string Nevada = "29";
        /// <summary>Lookup code: 30</summary>
        public const string Orange = "30";
        /// <summary>Lookup code: 31</summary>
        public const string Placer = "31";
        /// <summary>Lookup code: 32</summary>
        public const string Plumas = "32";
        /// <summary>Lookup code: 33</summary>
        public const string Riverside = "33";
        /// <summary>Lookup code: 34</summary>
        public const string Sacramento = "34";
        /// <summary>Lookup code: 35</summary>
        public const string SanBenito = "35";
        /// <summary>Lookup code: 36</summary>
        public const string SanBernardino = "36";
        /// <summary>Lookup code: 37</summary>
        public const string SanDiego = "37";
        /// <summary>Lookup code: 38</summary>
        public const string SanFrancisco = "38";
        /// <summary>Lookup code: 39</summary>
        public const string SanJoaquin = "39";
        /// <summary>Lookup code: 40</summary>
        public const string SanLuisObispo = "40";
        /// <summary>Lookup code: 41</summary>
        public const string SanMateo = "41";
        /// <summary>Lookup code: 42</summary>
        public const string SantaBarbara = "42";
        /// <summary>Lookup code: 43</summary>
        public const string SantaClara = "43";
        /// <summary>Lookup code: 44</summary>
        public const string SantaCruz = "44";
        /// <summary>Lookup code: 45</summary>
        public const string Shasta = "45";
        /// <summary>Lookup code: 46</summary>
        public const string Sierra = "46";
        /// <summary>Lookup code: 47</summary>
        public const string Siskiyou = "47";
        /// <summary>Lookup code: 48</summary>
        public const string Solano = "48";
        /// <summary>Lookup code: 49</summary>
        public const string Sonoma = "49";
        /// <summary>Lookup code: 50</summary>
        public const string Stanislaus = "50";
        /// <summary>Lookup code: 51</summary>
        public const string Sutter = "51";
        /// <summary>Lookup code: 52</summary>
        public const string Tehama = "52";
        /// <summary>Lookup code: 53</summary>
        public const string Trinity = "53";
        /// <summary>Lookup code: 54</summary>
        public const string Tulare = "54";
        /// <summary>Lookup code: 55</summary>
        public const string Tuolumne = "55";
        /// <summary>Lookup code: 56</summary>
        public const string Ventura = "56";
        /// <summary>Lookup code: 57</summary>
        public const string Yolo = "57";
        /// <summary>Lookup code: 58</summary>
        public const string Yuba = "58";
        /// <summary>Lookup code: 59</summary>
        public const string Marshall = "59";
        /// <summary>Lookup code: 60</summary>
        public const string Maury = "60";
        /// <summary>Lookup code: 61</summary>
        public const string Meigs = "61";
        /// <summary>Lookup code: 62</summary>
        public const string Monroe = "62";
        /// <summary>Lookup code: 63</summary>
        public const string Montgomery = "63";
        /// <summary>Lookup code: 64</summary>
        public const string Moore = "64";
        /// <summary>Lookup code: 65</summary>
        public const string Morgan = "65";
        /// <summary>Lookup code: 66</summary>
        public const string Obion = "66";
        /// <summary>Lookup code: 67</summary>
        public const string Overton = "67";
        /// <summary>Lookup code: 68</summary>
        public const string Perry = "68";
        /// <summary>Lookup code: 69</summary>
        public const string Pickett = "69";
        /// <summary>Lookup code: 70</summary>
        public const string Polk = "70";
        /// <summary>Lookup code: 71</summary>
        public const string Putnam = "71";
        /// <summary>Lookup code: 72</summary>
        public const string Rhea = "72";
        /// <summary>Lookup code: 73</summary>
        public const string Roane = "73";
        /// <summary>Lookup code: 74</summary>
        public const string Robertson = "74";
        /// <summary>Lookup code: 75</summary>
        public const string Rutherford = "75";
        /// <summary>Lookup code: 76</summary>
        public const string Scott = "76";
        /// <summary>Lookup code: 77</summary>
        public const string Sequatchie = "77";
        /// <summary>Lookup code: 78</summary>
        public const string Sevier = "78";
        /// <summary>Lookup code: 79</summary>
        public const string Shelby = "79";
        /// <summary>Lookup code: 80</summary>
        public const string Smith = "80";
        /// <summary>Lookup code: 81</summary>
        public const string Stewart = "81";
        /// <summary>Lookup code: 82</summary>
        public const string Sullivan = "82";
        /// <summary>Lookup code: 83</summary>
        public const string Sumner = "83";
        /// <summary>Lookup code: 84</summary>
        public const string Tipton = "84";
        /// <summary>Lookup code: 85</summary>
        public const string Trousdale = "85";
        /// <summary>Lookup code: 86</summary>
        public const string Unicoi = "86";
        /// <summary>Lookup code: 87</summary>
        public const string Union = "87";
        /// <summary>Lookup code: 88</summary>
        public const string VanBuren = "88";
        /// <summary>Lookup code: 89</summary>
        public const string Warren = "89";
        /// <summary>Lookup code: 90</summary>
        public const string Washington = "90";
        /// <summary>Lookup code: 91</summary>
        public const string Wayne = "91";
        /// <summary>Lookup code: 92</summary>
        public const string Weakley = "92";
        /// <summary>Lookup code: 93</summary>
        public const string White = "93";
        /// <summary>Lookup code: 94</summary>
        public const string Williamson = "94";
        /// <summary>Lookup code: 95</summary>
        public const string Wilson = "95";
    }

    /// <summary>Table of lookup properties for: County
    public static class LookupTable_County_Properties
    {
        /// <summary>Lookup property: CodeCategory</summary>
        public const string CodeCategory = "CodeCategory";
    }

    /// <summary>Table of lookup codes for: EmployerReportMethod
    public static class LookupTable_EmployerReportMethod
    {
        /// <summary>Lookup code: REIM</summary>
        public const string Reimbursable = "REIM";
        /// <summary>Lookup code: TAXP</summary>
        public const string Contributory = "TAXP";
    }

    /// <summary>Table of lookup properties for: EmployerReportMethod
    public static class LookupTable_EmployerReportMethod_Properties
    {
    }

    /// <summary>Table of lookup codes for: EmployerStatus
    public static class LookupTable_EmployerStatus
    {
        /// <summary>Lookup code: ACTV</summary>
        public const string Active = "ACTV";
        /// <summary>Lookup code: CANC</summary>
        public const string Cancelled = "CANC";
        /// <summary>Lookup code: CESD</summary>
        public const string Terminated = "CESD";
        /// <summary>Lookup code: EROR</summary>
        public const string Error = "EROR";
        /// <summary>Lookup code: EXPT</summary>
        public const string ExperienceTransfer = "EXPT";
        /// <summary>Lookup code: REAC</summary>
        public const string Reactivated = "REAC";
        /// <summary>Lookup code: REIN</summary>
        public const string Reinstated = "REIN";
        /// <summary>Lookup code: SUSP</summary>
        public const string Suspended = "SUSP";
        /// <summary>Lookup code: TERM</summary>
        public const string CompletlyTerminated = "TERM";
    }

    /// <summary>Table of lookup properties for: EmployerStatus
    public static class LookupTable_EmployerStatus_Properties
    {
    }

    /// <summary>Table of lookup codes for: FormType
    public static class LookupTable_FormType
    {
        /// <summary>Lookup code: FTVPW</summary>
        public const string VPWaiverForm = "FTVPW";
    }

    /// <summary>Table of lookup properties for: FormType
    public static class LookupTable_FormType_Properties
    {
    }

    /// <summary>Table of lookup codes for: LegalEntity
    public static class LookupTable_LegalEntity
    {
        /// <summary>Lookup code: ASTN</summary>
        public const string Association = "ASTN";
        /// <summary>Lookup code: CITY</summary>
        public const string City = "CITY";
        /// <summary>Lookup code: CNTY</summary>
        public const string County = "CNTY";
        /// <summary>Lookup code: CORP</summary>
        public const string Corporation = "CORP";
        /// <summary>Lookup code: GOVT</summary>
        public const string GovernmentStateAgency = "GOVT";
        /// <summary>Lookup code: GPTR</summary>
        public const string GeneralPartnership = "GPTR";
        /// <summary>Lookup code: LLBC</summary>
        public const string LimitedLiabilityCompany = "LLBC";
        /// <summary>Lookup code: LLBP</summary>
        public const string LimitedLiabilityPartnershipLLP = "LLBP";
        /// <summary>Lookup code: MLTY</summary>
        public const string USMilitary = "MLTY";
        /// <summary>Lookup code: PBLC</summary>
        public const string LocalPublicBody = "PBLC";
        /// <summary>Lookup code: SOLP</summary>
        public const string SoleProprietor = "SOLP";
        /// <summary>Lookup code: TRBP</summary>
        public const string IndianTribePuebloGovernment = "TRBP";
        /// <summary>Lookup code: TRST</summary>
        public const string Trust = "TRST";
    }

    /// <summary>Table of lookup properties for: LegalEntity
    public static class LookupTable_LegalEntity_Properties
    {
        /// <summary>Lookup property: DisplaySortOrder : To manipulate sort order</summary>
        public const string DisplaySortOrder = "DisplaySortOrder";
    }

    /// <summary>Table of lookup codes for: MakePaymentWizardFlow
    public static class LookupTable_MakePaymentWizardFlow
    {
        /// <summary>Lookup code: Complete</summary>
        public const string Complete = "Complete";
        /// <summary>Lookup code: Review Balance</summary>
        public const string ReviewBalance = "Review Balance";
        /// <summary>Lookup code: Select Pmt Method</summary>
        public const string SelectPaymentMethod = "Select Pmt Method";
        /// <summary>Lookup code: Submit Pmt Details</summary>
        public const string SubmitPaymentDetails = "Submit Pmt Details";
    }

    /// <summary>Table of lookup properties for: MakePaymentWizardFlow
    public static class LookupTable_MakePaymentWizardFlow_Properties
    {
        /// <summary>Lookup property: DisplaySortOrder : To manipulate sort order</summary>
        public const string DisplaySortOrder = "DisplaySortOrder";
    }

    /// <summary>Table of lookup codes for: MaritalStatus
    public static class LookupTable_MaritalStatus
    {
        /// <summary>Lookup code: DIV</summary>
        public const string Divorced = "DIV";
        /// <summary>Lookup code: MAR</summary>
        public const string Married = "MAR";
        /// <summary>Lookup code: SEP</summary>
        public const string Separated = "SEP";
        /// <summary>Lookup code: SNG</summary>
        public const string Single = "SNG";
        /// <summary>Lookup code: WID</summary>
        public const string Widowed = "WID";
    }

    /// <summary>Table of lookup properties for: MaritalStatus
    public static class LookupTable_MaritalStatus_Properties
    {
        /// <summary>Lookup property: CodeCategory</summary>
        public const string CodeCategory = "CodeCategory";
    }

    /// <summary>Table of lookup codes for: PaymentMethodType
    public static class LookupTable_PaymentMethodType
    {
        /// <summary>Lookup code: ACHD</summary>
        public const string ACHDebit = "ACHD";
        /// <summary>Lookup code: PCHK</summary>
        public const string PaperVoucher = "PCHK";
    }

    /// <summary>Table of lookup properties for: PaymentMethodType
    public static class LookupTable_PaymentMethodType_Properties
    {
    }

    /// <summary>Table of lookup codes for: PaymentStatus
    public static class LookupTable_PaymentStatus
    {
        /// <summary>Lookup code: Paid</summary>
        public const string PaymentStatusPaid = "Paid";
        /// <summary>Lookup code: Unpaid</summary>
        public const string PaymentStatusUnpaid = "Unpaid";
    }

    /// <summary>Table of lookup properties for: PaymentStatus
    public static class LookupTable_PaymentStatus_Properties
    {
    }

    /// <summary>Table of lookup codes for: PersonGender
    public static class LookupTable_PersonGender
    {
        /// <summary>Lookup code: F</summary>
        public const string Female = "F";
        /// <summary>Lookup code: M</summary>
        public const string Male = "M";
        /// <summary>Lookup code: U</summary>
        public const string Unknown = "U";
    }

    /// <summary>Table of lookup properties for: PersonGender
    public static class LookupTable_PersonGender_Properties
    {
    }

    /// <summary>Table of lookup codes for: PersonStatus
    public static class LookupTable_PersonStatus
    {
        /// <summary>Lookup code: ACTV</summary>
        public const string Active = "ACTV";
        /// <summary>Lookup code: DEAD</summary>
        public const string Deceased = "DEAD";
        /// <summary>Lookup code: INAC</summary>
        public const string Inactive = "INAC";
        /// <summary>Lookup code: PEND</summary>
        public const string Pending = "PEND";
    }

    /// <summary>Table of lookup properties for: PersonStatus
    public static class LookupTable_PersonStatus_Properties
    {
        /// <summary>Lookup property: DisplaySortOrder</summary>
        public const string DisplaySortOrder = "DisplaySortOrder";
    }

    /// <summary>Table of lookup codes for: PreferredCommunicationMethod
    public static class LookupTable_PreferredCommunicationMethod
    {
        /// <summary>Lookup code: Email</summary>
        public const string Email = "Email";
        /// <summary>Lookup code: Mail</summary>
        public const string Mail = "Mail";
    }

    /// <summary>Table of lookup properties for: PreferredCommunicationMethod
    public static class LookupTable_PreferredCommunicationMethod_Properties
    {
    }

    /// <summary>Table of lookup codes for: Prefix
    public static class LookupTable_Prefix
    {
        /// <summary>Lookup code: DR</summary>
        public const string DR = "DR";
        /// <summary>Lookup code: MR</summary>
        public const string MR = "MR";
        /// <summary>Lookup code: MRS</summary>
        public const string Mrs = "MRS";
        /// <summary>Lookup code: MS</summary>
        public const string MS = "MS";
    }

    /// <summary>Table of lookup properties for: Prefix
    public static class LookupTable_Prefix_Properties
    {
    }

    /// <summary>Table of lookup codes for: PremiumPaymentDueDays
    public static class LookupTable_PremiumPaymentDueDays
    {
        /// <summary>Lookup code: 10</summary>
        public const string PremiumPaymentDueDays = "10";
    }

    /// <summary>Table of lookup properties for: PremiumPaymentDueDays
    public static class LookupTable_PremiumPaymentDueDays_Properties
    {
    }

    /// <summary>Table of lookup codes for: Quarter
    public static class LookupTable_Quarter
    {
        /// <summary>Lookup code: Q1</summary>
        public const string JanuaryFebruaryMarchQ1 = "Q1";
        /// <summary>Lookup code: Q2</summary>
        public const string AprilMayJuneQ2 = "Q2";
        /// <summary>Lookup code: Q3</summary>
        public const string JulyAugustSeptemberQ3 = "Q3";
        /// <summary>Lookup code: Q4</summary>
        public const string OctoberNovemberDecemberQ4 = "Q4";
    }

    /// <summary>Table of lookup properties for: Quarter
    public static class LookupTable_Quarter_Properties
    {
        /// <summary>Lookup property: DisplaySortOrder : To manipulate sort order</summary>
        public const string DisplaySortOrder = "DisplaySortOrder";
    }

    /// <summary>Table of lookup codes for: State
    public static class LookupTable_State
    {
        /// <summary>Lookup code: AA</summary>
        public const string ArmedForcesAmerica = "AA";
        /// <summary>Lookup code: AE</summary>
        public const string ArmedForcesEurope = "AE";
        /// <summary>Lookup code: AK</summary>
        public const string Alaska = "AK";
        /// <summary>Lookup code: AL</summary>
        public const string Alabama = "AL";
        /// <summary>Lookup code: AP</summary>
        public const string ArmedForcesPacific = "AP";
        /// <summary>Lookup code: AR</summary>
        public const string Arkansas = "AR";
        /// <summary>Lookup code: AS</summary>
        public const string AmericanSamoa = "AS";
        /// <summary>Lookup code: AZ</summary>
        public const string Arizona = "AZ";
        /// <summary>Lookup code: CA</summary>
        public const string California = "CA";
        /// <summary>Lookup code: CO</summary>
        public const string Colorado = "CO";
        /// <summary>Lookup code: CT</summary>
        public const string Connecticut = "CT";
        /// <summary>Lookup code: DC</summary>
        public const string DistrictofColumbia = "DC";
        /// <summary>Lookup code: DE</summary>
        public const string Delaware = "DE";
        /// <summary>Lookup code: FL</summary>
        public const string Florida = "FL";
        /// <summary>Lookup code: FM</summary>
        public const string FederatedStatesofMicronesia = "FM";
        /// <summary>Lookup code: GA</summary>
        public const string Georgia = "GA";
        /// <summary>Lookup code: GU</summary>
        public const string Guam = "GU";
        /// <summary>Lookup code: HI</summary>
        public const string Hawaii = "HI";
        /// <summary>Lookup code: IA</summary>
        public const string Iowa = "IA";
        /// <summary>Lookup code: ID</summary>
        public const string Idaho = "ID";
        /// <summary>Lookup code: IL</summary>
        public const string Illinois = "IL";
        /// <summary>Lookup code: IN</summary>
        public const string Indiana = "IN";
        /// <summary>Lookup code: KS</summary>
        public const string Kansas = "KS";
        /// <summary>Lookup code: KY</summary>
        public const string Kentucky = "KY";
        /// <summary>Lookup code: LA</summary>
        public const string Louisiana = "LA";
        /// <summary>Lookup code: MA</summary>
        public const string Massachusetts = "MA";
        /// <summary>Lookup code: MD</summary>
        public const string Maryland = "MD";
        /// <summary>Lookup code: ME</summary>
        public const string Maine = "ME";
        /// <summary>Lookup code: MH</summary>
        public const string MarshallIslands = "MH";
        /// <summary>Lookup code: MI</summary>
        public const string Michigan = "MI";
        /// <summary>Lookup code: MN</summary>
        public const string Minnesota = "MN";
        /// <summary>Lookup code: MO</summary>
        public const string Missouri = "MO";
        /// <summary>Lookup code: MP</summary>
        public const string NorthernMarianaIslands = "MP";
        /// <summary>Lookup code: MS</summary>
        public const string Mississippi = "MS";
        /// <summary>Lookup code: MT</summary>
        public const string Montana = "MT";
        /// <summary>Lookup code: NC</summary>
        public const string NorthCarolina = "NC";
        /// <summary>Lookup code: ND</summary>
        public const string NorthDakota = "ND";
        /// <summary>Lookup code: NE</summary>
        public const string Nebraska = "NE";
        /// <summary>Lookup code: NH</summary>
        public const string NewHampshire = "NH";
        /// <summary>Lookup code: NJ</summary>
        public const string NewJersey = "NJ";
        /// <summary>Lookup code: NM</summary>
        public const string NewMexico = "NM";
        /// <summary>Lookup code: NV</summary>
        public const string Nevada = "NV";
        /// <summary>Lookup code: NY</summary>
        public const string NewYork = "NY";
        /// <summary>Lookup code: OH</summary>
        public const string Ohio = "OH";
        /// <summary>Lookup code: OK</summary>
        public const string Oklahoma = "OK";
        /// <summary>Lookup code: OR</summary>
        public const string Oregon = "OR";
        /// <summary>Lookup code: PA</summary>
        public const string Pennsylvania = "PA";
        /// <summary>Lookup code: PR</summary>
        public const string PuertoRico = "PR";
        /// <summary>Lookup code: PW</summary>
        public const string Palau = "PW";
        /// <summary>Lookup code: RI</summary>
        public const string RhodeIsland = "RI";
        /// <summary>Lookup code: SC</summary>
        public const string SouthCarolina = "SC";
        /// <summary>Lookup code: SD</summary>
        public const string SouthDakota = "SD";
        /// <summary>Lookup code: TN</summary>
        public const string Tennessee = "TN";
        /// <summary>Lookup code: TX</summary>
        public const string Texas = "TX";
        /// <summary>Lookup code: UT</summary>
        public const string Utah = "UT";
        /// <summary>Lookup code: VA</summary>
        public const string Virginia = "VA";
        /// <summary>Lookup code: VI</summary>
        public const string VirginIslands = "VI";
        /// <summary>Lookup code: VT</summary>
        public const string Vermont = "VT";
        /// <summary>Lookup code: WA</summary>
        public const string Washington = "WA";
        /// <summary>Lookup code: WI</summary>
        public const string Wisconsin = "WI";
        /// <summary>Lookup code: WV</summary>
        public const string WestVirginia = "WV";
        /// <summary>Lookup code: WY</summary>
        public const string Wyoming = "WY";
    }

    /// <summary>Table of lookup properties for: State
    public static class LookupTable_State_Properties
    {
        /// <summary>Lookup property: ReciprocalStateInd : Indicates reciprocal state</summary>
        public const string ReciprocalStateInd = "ReciprocalStateInd";
    }

    /// <summary>Table of lookup codes for: StatePrvnc
    public static class LookupTable_StatePrvnc
    {
        /// <summary>Lookup code: AA</summary>
        public const string ArmedForcesAmerica = "AA";
        /// <summary>Lookup code: AB</summary>
        public const string Alberta = "AB";
        /// <summary>Lookup code: AE</summary>
        public const string ArmedForcesEurope = "AE";
        /// <summary>Lookup code: AK</summary>
        public const string Alaska = "AK";
        /// <summary>Lookup code: AL</summary>
        public const string Alabama = "AL";
        /// <summary>Lookup code: AP</summary>
        public const string ArmedForcesPacific = "AP";
        /// <summary>Lookup code: AR</summary>
        public const string Arkansas = "AR";
        /// <summary>Lookup code: AZ</summary>
        public const string Arizona = "AZ";
        /// <summary>Lookup code: BC</summary>
        public const string BritishColumbia = "BC";
        /// <summary>Lookup code: CA</summary>
        public const string California = "CA";
        /// <summary>Lookup code: CO</summary>
        public const string Colorado = "CO";
        /// <summary>Lookup code: CT</summary>
        public const string Connecticut = "CT";
        /// <summary>Lookup code: DC</summary>
        public const string DistrictofColumbia = "DC";
        /// <summary>Lookup code: DE</summary>
        public const string Delaware = "DE";
        /// <summary>Lookup code: FL</summary>
        public const string Florida = "FL";
        /// <summary>Lookup code: GA</summary>
        public const string Georgia = "GA";
        /// <summary>Lookup code: GU</summary>
        public const string Guam = "GU";
        /// <summary>Lookup code: HI</summary>
        public const string Hawaii = "HI";
        /// <summary>Lookup code: IA</summary>
        public const string Iowa = "IA";
        /// <summary>Lookup code: ID</summary>
        public const string Idaho = "ID";
        /// <summary>Lookup code: IL</summary>
        public const string Illinois = "IL";
        /// <summary>Lookup code: IN</summary>
        public const string Indiana = "IN";
        /// <summary>Lookup code: KS</summary>
        public const string Kansas = "KS";
        /// <summary>Lookup code: KY</summary>
        public const string Kentucky = "KY";
        /// <summary>Lookup code: LA</summary>
        public const string Louisiana = "LA";
        /// <summary>Lookup code: MA</summary>
        public const string Massachusetts = "MA";
        /// <summary>Lookup code: MB</summary>
        public const string Manitoba = "MB";
        /// <summary>Lookup code: MD</summary>
        public const string Maryland = "MD";
        /// <summary>Lookup code: ME</summary>
        public const string Maine = "ME";
        /// <summary>Lookup code: MI</summary>
        public const string Michigan = "MI";
        /// <summary>Lookup code: MN</summary>
        public const string Minnesota = "MN";
        /// <summary>Lookup code: MO</summary>
        public const string Missouri = "MO";
        /// <summary>Lookup code: MS</summary>
        public const string Mississippi = "MS";
        /// <summary>Lookup code: MT</summary>
        public const string Montana = "MT";
        /// <summary>Lookup code: NB</summary>
        public const string NewBrunswick = "NB";
        /// <summary>Lookup code: NC</summary>
        public const string NorthCarolina = "NC";
        /// <summary>Lookup code: ND</summary>
        public const string NorthDakota = "ND";
        /// <summary>Lookup code: NE</summary>
        public const string Nebraska = "NE";
        /// <summary>Lookup code: NF</summary>
        public const string Newfoundland = "NF";
        /// <summary>Lookup code: NH</summary>
        public const string NewHampshire = "NH";
        /// <summary>Lookup code: NJ</summary>
        public const string NewJersey = "NJ";
        /// <summary>Lookup code: NM</summary>
        public const string NewMexico = "NM";
        /// <summary>Lookup code: NS</summary>
        public const string NovaScotia = "NS";
        /// <summary>Lookup code: NT</summary>
        public const string NorthwestTerritories = "NT";
        /// <summary>Lookup code: NU</summary>
        public const string Nunavut = "NU";
        /// <summary>Lookup code: NV</summary>
        public const string Nevada = "NV";
        /// <summary>Lookup code: NY</summary>
        public const string NewYork = "NY";
        /// <summary>Lookup code: OH</summary>
        public const string Ohio = "OH";
        /// <summary>Lookup code: OK</summary>
        public const string Oklahoma = "OK";
        /// <summary>Lookup code: ON</summary>
        public const string Ontario = "ON";
        /// <summary>Lookup code: OR</summary>
        public const string Oregon = "OR";
        /// <summary>Lookup code: PA</summary>
        public const string Pennsylvania = "PA";
        /// <summary>Lookup code: PE</summary>
        public const string PrinceEdwardIsland = "PE";
        /// <summary>Lookup code: PR</summary>
        public const string PuertoRico = "PR";
        /// <summary>Lookup code: QC</summary>
        public const string Quebec = "QC";
        /// <summary>Lookup code: RI</summary>
        public const string RhodeIsland = "RI";
        /// <summary>Lookup code: SC</summary>
        public const string SouthCarolina = "SC";
        /// <summary>Lookup code: SD</summary>
        public const string SouthDakota = "SD";
        /// <summary>Lookup code: SK</summary>
        public const string Saskatchewan = "SK";
        /// <summary>Lookup code: TN</summary>
        public const string Tennessee = "TN";
        /// <summary>Lookup code: TX</summary>
        public const string Texas = "TX";
        /// <summary>Lookup code: UT</summary>
        public const string Utah = "UT";
        /// <summary>Lookup code: VA</summary>
        public const string Virginia = "VA";
        /// <summary>Lookup code: VI</summary>
        public const string VirginIslands = "VI";
        /// <summary>Lookup code: VT</summary>
        public const string Vermont = "VT";
        /// <summary>Lookup code: WA</summary>
        public const string Washington = "WA";
        /// <summary>Lookup code: WI</summary>
        public const string Wisconsin = "WI";
        /// <summary>Lookup code: WV</summary>
        public const string WestVirginia = "WV";
        /// <summary>Lookup code: WY</summary>
        public const string Wyoming = "WY";
        /// <summary>Lookup code: YT</summary>
        public const string YukonTerritory = "YT";
    }

    /// <summary>Table of lookup properties for: StatePrvnc
    public static class LookupTable_StatePrvnc_Properties
    {
        /// <summary>Lookup property: Type : To identify country</summary>
        public const string Type = "Type";
    }

    /// <summary>Table of lookup codes for: Suffix
    public static class LookupTable_Suffix
    {
        /// <summary>Lookup code: II</summary>
        public const string II = "II";
        /// <summary>Lookup code: III</summary>
        public const string Iii = "III";
        /// <summary>Lookup code: IV</summary>
        public const string IV = "IV";
        /// <summary>Lookup code: JD</summary>
        public const string JD = "JD";
        /// <summary>Lookup code: JR</summary>
        public const string JR = "JR";
        /// <summary>Lookup code: SR</summary>
        public const string SR = "SR";
        /// <summary>Lookup code: Test</summary>
        public const string Test = "Test";
        /// <summary>Lookup code: V</summary>
        public const string V = "V";
        /// <summary>Lookup code: VI</summary>
        public const string VI = "VI";
    }

    /// <summary>Table of lookup properties for: Suffix
    public static class LookupTable_Suffix_Properties
    {
    }

    /// <summary>Table of lookup codes for: TaxableAmSumStatus
    public static class LookupTable_TaxableAmSumStatus
    {
        /// <summary>Lookup code: Submitted</summary>
        public const string Submitted = "Submitted";
    }

    /// <summary>Table of lookup properties for: TaxableAmSumStatus
    public static class LookupTable_TaxableAmSumStatus_Properties
    {
    }

    /// <summary>Table of lookup codes for: TransactionType
    public static class LookupTable_TransactionType
    {
        /// <summary>Lookup code: ContrPrin</summary>
        public const string ContributionsPrinciple = "ContrPrin";
    }

    /// <summary>Table of lookup properties for: TransactionType
    public static class LookupTable_TransactionType_Properties
    {
    }

    /// <summary>Table of lookup codes for: ValidationType
    public static class LookupTable_ValidationType
    {
        /// <summary>Lookup code: ADDRESS</summary>
        public const string Mailingaddress = "ADDRESS";
        /// <summary>Lookup code: EMAIL</summary>
        public const string EmailAddress = "EMAIL";
        /// <summary>Lookup code: PHONE</summary>
        public const string PhoneNumber = "PHONE";
    }

    /// <summary>Table of lookup properties for: ValidationType
    public static class LookupTable_ValidationType_Properties
    {
    }

    /// <summary>Table of lookup codes for: WageDetailAdjReasonCode
    public static class LookupTable_WageDetailAdjReasonCode
    {
        /// <summary>Lookup code: Orig</summary>
        public const string Original = "Orig";
    }

    /// <summary>Table of lookup properties for: WageDetailAdjReasonCode
    public static class LookupTable_WageDetailAdjReasonCode_Properties
    {
    }

    /// <summary>Table of lookup codes for: WageDetailFilingMethod
    public static class LookupTable_WageDetailFilingMethod
    {
        /// <summary>Lookup code: Copy</summary>
        public const string CopyfromPreviousQuarter = "Copy";
        /// <summary>Lookup code: Manu</summary>
        public const string ManualEntry = "Manu";
        /// <summary>Lookup code: NEmp</summary>
        public const string NoEmploymentandNoWage = "NEmp";
        /// <summary>Lookup code: Upld</summary>
        public const string FileUpload = "Upld";
    }

    /// <summary>Table of lookup properties for: WageDetailFilingMethod
    public static class LookupTable_WageDetailFilingMethod_Properties
    {
        /// <summary>Lookup property: DisplaySortOrder : To manipulate sort order</summary>
        public const string DisplaySortOrder = "DisplaySortOrder";
    }

    /// <summary>Table of lookup codes for: WageDetailUnitYears
    public static class LookupTable_WageDetailUnitYears
    {
        /// <summary>Lookup code: 4</summary>
        public const string YearsForWageFiling = "4";
    }

    /// <summary>Table of lookup properties for: WageDetailUnitYears
    public static class LookupTable_WageDetailUnitYears_Properties
    {
    }

    /// <summary>Table of lookup codes for: WaiverLeaveType
    public static class LookupTable_WaiverLeaveType
    {
        /// <summary>Lookup code: WLTCar</summary>
        public const string Caregiver = "WLTCar";
        /// <summary>Lookup code: WLTMed</summary>
        public const string Medical = "WLTMed";
        /// <summary>Lookup code: WLTPaa</summary>
        public const string PaternityAdoption = "WLTPaa";
        /// <summary>Lookup code: WLTPab</summary>
        public const string PaternityBirthFather = "WLTPab";
    }

    /// <summary>Table of lookup properties for: WaiverLeaveType
    public static class LookupTable_WaiverLeaveType_Properties
    {
    }

    /// <summary>Table of lookup codes for: WaiverRequestStatus
    public static class LookupTable_WaiverRequestStatus
    {
        /// <summary>Lookup code: WRSApr</summary>
        public const string Approved = "WRSApr";
        /// <summary>Lookup code: WRSDen</summary>
        public const string Denied = "WRSDen";
        /// <summary>Lookup code: WRSRev</summary>
        public const string ReviewinProgress = "WRSRev";
        /// <summary>Lookup code: WRSSad</summary>
        public const string SavedasDraft = "WRSSad";
        /// <summary>Lookup code: WRSSub</summary>
        public const string SubmittedforPayment = "WRSSub";
    }

    /// <summary>Table of lookup properties for: WaiverRequestStatus
    public static class LookupTable_WaiverRequestStatus_Properties
    {
    }

    /// <summary>Table of lookup codes for: WaiverWeeksAvailable
    public static class LookupTable_WaiverWeeksAvailable
    {
        /// <summary>Lookup code: WWAA</summary>
        public const string _1Week = "WWAA";
        /// <summary>Lookup code: WWAB</summary>
        public const string _2Weeks = "WWAB";
        /// <summary>Lookup code: WWAC</summary>
        public const string _3Weeks = "WWAC";
        /// <summary>Lookup code: WWAD</summary>
        public const string _4Weeks = "WWAD";
        /// <summary>Lookup code: WWAE</summary>
        public const string _5Weeks = "WWAE";
        /// <summary>Lookup code: WWAF</summary>
        public const string _6Weeks = "WWAF";
        /// <summary>Lookup code: WWAG</summary>
        public const string _7Weeks = "WWAG";
        /// <summary>Lookup code: WWAH</summary>
        public const string _8Weeks = "WWAH";
    }

    /// <summary>Table of lookup properties for: WaiverWeeksAvailable
    public static class LookupTable_WaiverWeeksAvailable_Properties
    {
    }

    /// <summary>Table of lookup codes for: WizEmployerRegistration
    public static class LookupTable_WizEmployerRegistration
    {
        /// <summary>Lookup code: Complete</summary>
        public const string Complete = "Complete";
        /// <summary>Lookup code: EntBusInfo</summary>
        public const string EnterBusinessInformation = "EntBusInfo";
        /// <summary>Lookup code: EntEmpInfo</summary>
        public const string EnterEmployerInformation = "EntEmpInfo";
        /// <summary>Lookup code: EntLblInfo</summary>
        public const string EnterLiabilityInformation = "EntLblInfo";
        /// <summary>Lookup code: EntUsers</summary>
        public const string EnterUsers = "EntUsers";
        /// <summary>Lookup code: Summary</summary>
        public const string Summary = "Summary";
    }

    /// <summary>Table of lookup properties for: WizEmployerRegistration
    public static class LookupTable_WizEmployerRegistration_Properties
    {
        /// <summary>Lookup property: DisplaySortOrder : To manipulate sort order</summary>
        public const string DisplaySortOrder = "DisplaySortOrder";
    }

    /// <summary>Table of lookup codes for: WizEmployerWageFiling
    public static class LookupTable_WizEmployerWageFiling
    {
        /// <summary>Lookup code: CnfrmSub</summary>
        public const string ConfirmSubmission = "CnfrmSub";
        /// <summary>Lookup code: PrcAndCalc</summary>
        public const string ProcessandCalculate = "PrcAndCalc";
        /// <summary>Lookup code: SelFilMthd</summary>
        public const string SelectFilingMethod = "SelFilMthd";
        /// <summary>Lookup code: SubWgInfo</summary>
        public const string SubmitWageInformation = "SubWgInfo";
    }

    /// <summary>Table of lookup properties for: WizEmployerWageFiling
    public static class LookupTable_WizEmployerWageFiling_Properties
    {
        /// <summary>Lookup property: DisplaySortOrder : To manipulate sort order</summary>
        public const string DisplaySortOrder = "DisplaySortOrder";
    }

}
