// ----------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a compiler emitter: FACTS.Framework.Analysis.Generators.OperationMethod.ControllerEmitter
//
// Changes to this file may cause incorrect behavior and will be lost when the code is regenerated.
// </auto-generated>
// ----------------------------------------------------------------------------------------------------

using System;
using Microsoft.AspNetCore.Mvc;
using FACTS.Framework.Service;

namespace PFML.Service.Controllers.Premium.MakePayment
{

    public class MakePaymentController : Controller
    {

        [HttpPost]
        [Route("Premium/MakePayment/GetEmployerDueAmount")]
        [OperationMethodFilter]
        public PFML.Shared.ViewModels.Premium.Payments.MakePayment.MakePaymentViewModel GetEmployerDueAmount([FromBody]int emprAccountID)
        {
            return PFML.BusinessLogic.Premium.MakePayment.MakePaymentLogic.GetEmployerDueAmount(emprAccountID);
        }

    }

}
